# Generated by Django 5.1.6 on 2025-03-05 12:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0002_initial'),
        ('competition', '0004_alter_scoreuser_solved_challenges'),
    ]

    operations = [
        migrations.AddField(
            model_name='challengecomment',
            name='competition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='challenge_comments', to='competition.competition', verbose_name='所属比赛'),
        ),
    ]
