# Generated by Django 5.1.6 on 2026-03-08 18:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ToolCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='工具分类名称')),
                ('key', models.CharField(help_text='英文标识，如：office, auxiliary, develop, web', max_length=50, unique=True, verbose_name='分类标识')),
                ('order_num', models.IntegerField(default=99, help_text='序号可以用来调整顺序，越小越靠前', verbose_name='序号')),
                ('icon', models.CharField(blank=True, default='fa fa-link', max_length=50, null=True, verbose_name='图标')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '工具分类',
                'verbose_name_plural': '工具分类',
                'ordering': ['order_num', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Tool',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='工具名称')),
                ('description', models.CharField(max_length=200, verbose_name='工具描述')),
                ('tool_type', models.CharField(choices=[('internal', '内部工具'), ('external', '外部链接')], default='internal', max_length=20, verbose_name='工具类型')),
                ('url_name', models.CharField(blank=True, help_text='Django URL名称，如：tool:markdown_editor', max_length=100, null=True, verbose_name='URL路由名称')),
                ('external_url', models.URLField(blank=True, help_text='外部工具的完整URL地址', null=True, verbose_name='外部链接')),
                ('icon', models.CharField(help_text='Font Awesome图标类名，如：fa fa-link, fa fa-code, fa fa-wrench 等。参考：https://fontawesome.com/icons', max_length=200, verbose_name='工具图标')),
                ('order_num', models.IntegerField(default=99, help_text='序号可以用来调整顺序，越小越靠前', verbose_name='序号')),
                ('is_published', models.BooleanField(default=True, help_text='控制工具是否在前台显示', verbose_name='是否发布')),
                ('is_admin_only', models.BooleanField(default=False, help_text='勾选后只有管理员能在前端看到此工具', verbose_name='仅管理员可见')),
                ('views', models.PositiveIntegerField(default=0, verbose_name='浏览次数')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tools', to='tool.toolcategory', verbose_name='工具分类')),
            ],
            options={
                'verbose_name': '在线工具',
                'verbose_name_plural': '在线工具',
                'ordering': ['category__order_num', 'order_num', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ToolLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='网站名称')),
                ('description', models.CharField(max_length=100, verbose_name='网站描述')),
                ('link', models.URLField(verbose_name='网站链接')),
                ('order_num', models.IntegerField(default=99, help_text='序号可以用来调整顺序，越小越靠前', verbose_name='序号')),
                ('is_admin_only', models.BooleanField(default=False, help_text='勾选后只有管理员能在前端看到此工具链接', verbose_name='仅管理员可见')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tool.toolcategory', verbose_name='网站分类')),
            ],
            options={
                'verbose_name': '工具链接',
                'verbose_name_plural': '工具链接',
                'ordering': ['order_num', 'id'],
            },
        ),
    ]
