# Generated by Django 5.1.6 on 2026-03-08 18:21

import competition.models
import django.core.validators
import django.utils.timezone
import imagekit.models.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Challenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(default=competition.models.generate_short_uuid, editable=False, max_length=16, unique=True, verbose_name='唯一标识符')),
                ('title', models.CharField(max_length=255, verbose_name='题目标题')),
                ('description', models.TextField(verbose_name='题目描述')),
                ('category', models.CharField(choices=[('签到', '签到'), ('Web', 'Web'), ('Pwn', 'Pwn'), ('逆向', '逆向工程'), ('密码学', '密码学'), ('杂项', '杂项'), ('综合渗透', '综合渗透'), ('数字取证', '数字取证'), ('内存取证', '内存取证'), ('磁盘取证', '磁盘取证'), ('流量分析', '流量分析'), ('日志分析', '日志分析'), ('移动安全', '移动安全'), ('Android', 'Android'), ('iOS', 'iOS'), ('物联网', '物联网'), ('区块链', '区块链'), ('智能合约', '智能合约'), ('云安全', '云安全'), ('容器安全', '容器安全'), ('AI安全', 'AI安全'), ('机器学习', '机器学习'), ('开源情报', '开源情报'), ('隐写术', '隐写术'), ('编程', '编程'), ('硬件安全', '硬件安全'), ('无线电', '无线电'), ('CVE复现', 'CVE复现'), ('渗透测试', '渗透测试'), ('红队', '红队'), ('蓝队', '蓝队'), ('AD域渗透', 'AD域渗透'), ('内网渗透', '内网渗透'), ('Web3', 'Web3'), ('元宇宙', '元宇宙'), ('游戏安全', '游戏安全'), ('车联网', '车联网'), ('其他', '其他')], default='WEB', max_length=20, verbose_name='题目类型')),
                ('difficulty', models.CharField(choices=[('Easy', '简单'), ('Medium', '中等'), ('Hard', '困难')], default='Medium', max_length=10, verbose_name='难度')),
                ('flag_type', models.CharField(choices=[('STATIC', '静态Flag'), ('DYNAMIC', '动态flag')], default='DYNAMIC', max_length=20, verbose_name='Flag类型')),
                ('initial_points', models.IntegerField(default=500, help_text='题目初始分数，范围：200-1000分', verbose_name='初始分数')),
                ('minimum_points', models.IntegerField(default=100, help_text='题目最低分数，不能低于50分', verbose_name='最低分数')),
                ('points', models.IntegerField(blank=True, default=None, help_text='随解题人数动态变化的分数', null=True, verbose_name='当前动态分数')),
                ('solves', models.IntegerField(default=0, verbose_name='解决次数')),
                ('flag_template', models.CharField(blank=True, help_text='用于生成动态Flag的模板', max_length=255, null=True, verbose_name='Flag值')),
                ('static_file_url', models.URLField(blank=True, help_text='填写静态文件的URL地址，如果填写了URL地址，则优先使用URL地址，否则使用静态文件', max_length=500, null=True, verbose_name='静态文件URL')),
                ('hint', models.TextField(blank=True, null=True, verbose_name='提示')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否激活')),
                ('is_top', models.BooleanField(default=False, verbose_name='置顶')),
            ],
            options={
                'verbose_name': '题目配置',
                'verbose_name_plural': '题目配置',
            },
        ),
        migrations.CreateModel(
            name='CheatingLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cheating_type', models.CharField(choices=[('timing', '暴力提交'), ('exploit', '攻击系统'), ('bot', '机器人行为'), ('manual', '提交Ta人FLAG'), ('ipyichang', 'IP异常'), ('file_not_downloaded', '未下载文件提交')], max_length=50, verbose_name='作弊类型')),
                ('description', models.TextField(verbose_name='描述')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, verbose_name='记录时间')),
                ('detected_by', models.CharField(default='System', max_length=100, verbose_name='检测者')),
            ],
            options={
                'verbose_name': '监控日志',
                'verbose_name_plural': '监控日志',
            },
        ),
        migrations.CreateModel(
            name='CombinedLeaderboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ctf_score', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='竞赛分数')),
                ('quiz_score', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='知识竞赛分数')),
                ('combined_score', models.DecimalField(db_index=True, decimal_places=2, default=0, help_text='归一化后的综合得分（0-100分）', max_digits=10, verbose_name='综合分数')),
                ('rank', models.IntegerField(db_index=True, default=0, verbose_name='排名')),
                ('ctf_rank', models.IntegerField(default=0, verbose_name='CTF排名')),
                ('quiz_rank', models.IntegerField(default=0, verbose_name='知识竞赛排名')),
                ('is_final', models.BooleanField(db_index=True, default=False, help_text='比赛结束后的数据标记为最终，不可变更', verbose_name='是否为最终数据')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '综合排行榜',
                'verbose_name_plural': '综合排行榜',
                'ordering': ['rank', '-combined_score'],
            },
        ),
        migrations.CreateModel(
            name='Competition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='比赛标题')),
                ('description', models.TextField(verbose_name='比赛描述')),
                ('img_link', imagekit.models.fields.ProcessedImageField(blank=True, default='public/default/default.png', help_text='上传图片大小建议使用5:3的宽高比，为了清晰度原始图片宽度应该超过250px', upload_to='competition/upload/%Y/%m/%d/', verbose_name='封面图')),
                ('start_time', models.DateTimeField(verbose_name='比赛开始时间')),
                ('end_time', models.DateTimeField(verbose_name='比赛结束时间')),
                ('is_active', models.BooleanField(default=True, verbose_name='激活竞赛')),
                ('is_register', models.BooleanField(default=True, verbose_name='是否允许报名')),
                ('is_audit', models.BooleanField(choices=[(True, '需要审核'), (False, '不需要审核')], default=False, verbose_name='比赛报名是否需要审核')),
                ('invitation_code', models.CharField(blank=True, max_length=255, null=True, verbose_name='邀请码')),
                ('slug', models.SlugField(blank=True, null=True, unique=True, verbose_name='路由')),
                ('re_slug', models.SlugField(blank=True, null=True, unique=True, verbose_name='报名路由')),
                ('competition_type', models.CharField(choices=[('individual', '个人赛'), ('team', '团体赛')], default='team', help_text='选择比赛类型：个人赛或团体赛', max_length=10, verbose_name='比赛类型')),
                ('team_max_members', models.IntegerField(choices=[(2, '2人'), (3, '3人'), (4, '4人')], default=4, help_text='团队赛中每个队伍的最大人数（2-4人），仅在团队赛时生效', verbose_name='队伍最大人数')),
                ('visibility_type', models.CharField(choices=[('public', '公开赛'), ('internal', '内部赛')], default='public', help_text='选择比赛类型：公开赛或内部赛', max_length=10, verbose_name='公开类型')),
                ('theme', models.CharField(choices=[('default', '简约风格'), ('tech', '科技风格')], default='tech', help_text='选择比赛前端展示风格', max_length=20, verbose_name='前端风格')),
                ('dashboard_template', models.CharField(choices=[('dashboardone', '大屏模板1'), ('dashboardtwo', '大屏模板2')], default='dashboardone', help_text='选择数据大屏展示模板', max_length=20, verbose_name='大屏模板')),
                ('combined_score_ctf_weight', models.DecimalField(decimal_places=2, default=0.6, help_text='综合分数中CTF所占权重（0-1之间，建议0.6）', max_digits=3, verbose_name='CTF权重')),
                ('combined_score_top_percent', models.IntegerField(default=20, help_text='取前百分之几的平均分作为归一化基准（建议10-30之间）', verbose_name='归一化基准百分比')),
            ],
            options={
                'verbose_name': '竞赛配置',
                'verbose_name_plural': '竞赛配置',
                'ordering': ['-start_time'],
            },
        ),
        migrations.CreateModel(
            name='LeaderboardCalculationTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', '待处理'), ('running', '计算中'), ('completed', '已完成'), ('failed', '失败'), ('cancelled', '已取消')], db_index=True, default='pending', max_length=20, verbose_name='状态')),
                ('competition_type', models.CharField(help_text='individual或team', max_length=20, verbose_name='竞赛类型')),
                ('total_participants', models.IntegerField(default=0, verbose_name='参与者总数')),
                ('processed_count', models.IntegerField(default=0, verbose_name='已处理数量')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='开始时间')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('result_count', models.IntegerField(default=0, verbose_name='结果数量')),
                ('error_message', models.TextField(blank=True, verbose_name='错误信息')),
                ('data_version', models.CharField(db_index=True, help_text='基于CTF和Quiz数据的哈希值', max_length=64, verbose_name='数据版本')),
                ('idempotency_key', models.CharField(db_index=True, help_text='确保相同条件下不会重复计算', max_length=128, unique=True, verbose_name='幂等性键')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '排行榜计算任务',
                'verbose_name_plural': '排行榜计算任务',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_type', models.CharField(choices=[('individual', '个人报名'), ('team', '团队报名')], default='individual', help_text='选择报名类型：个人报名或团队报名', max_length=10, verbose_name='报名类型')),
                ('is_audit', models.BooleanField(default=False, verbose_name='是否需要审核')),
                ('audit', models.BooleanField(choices=[(True, '通过'), (False, '未通过')], default=False, verbose_name='审核状态')),
                ('audit_comment', models.TextField(blank=True, null=True, verbose_name='审核备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='报名时间')),
            ],
            options={
                'verbose_name': '竞赛报名',
                'verbose_name_plural': '竞赛报名',
            },
        ),
        migrations.CreateModel(
            name='ScoreTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(verbose_name='队伍得分')),
                ('time', models.DateTimeField(auto_now_add=True, verbose_name='最近得分时间')),
                ('rank', models.IntegerField(default=0, verbose_name='队伍排名')),
            ],
            options={
                'verbose_name': '队伍计分',
                'verbose_name_plural': '队伍计分',
            },
        ),
        migrations.CreateModel(
            name='ScoreUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.IntegerField(default=0, verbose_name='得分')),
                ('rank', models.IntegerField(default=0, verbose_name='用户排名')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='得分时间')),
            ],
            options={
                'verbose_name': '个人计分',
                'verbose_name_plural': '个人计分',
            },
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flag', models.CharField(max_length=255, verbose_name='提交的Flag')),
                ('status', models.CharField(choices=[('correct', '正确'), ('wrong', '错误'), ('pending', '待判定')], default='pending', max_length=10, verbose_name='状态')),
                ('ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='提交IP')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='提交时间')),
                ('points_earned', models.IntegerField(default=0, verbose_name='获得分数')),
                ('base_score', models.IntegerField(default=0, help_text='动态基础分', verbose_name='基础分数')),
                ('blood_bonus', models.IntegerField(default=0, help_text='一二三血奖励', verbose_name='血榜奖励')),
                ('time_bonus', models.IntegerField(default=0, help_text='时间奖励分', verbose_name='时间奖励')),
                ('solve_rank', models.IntegerField(default=0, help_text='第几个解出的', verbose_name='解题排名')),
            ],
            options={
                'verbose_name': '提交记录',
                'verbose_name_plural': '提交记录',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True, verbose_name='文章标签')),
                ('description', models.TextField(default='标签描述', help_text='用来作为SEO中description,长度参考SEO标准', max_length=240, verbose_name='描述')),
            ],
            options={
                'verbose_name': '标签配置',
                'verbose_name_plural': '标签配置',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='队伍名称')),
                ('team_code', models.CharField(blank=True, max_length=6, null=True, unique=True, verbose_name='队伍认证码')),
                ('member_count', models.IntegerField(default=4, verbose_name='队伍成员最大数量')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '队伍配置',
                'verbose_name_plural': '队伍配置',
            },
        ),
        migrations.CreateModel(
            name='Writeup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Writeup标题')),
                ('description', models.TextField(blank=True, verbose_name='Writeup简介')),
                ('pdf_file', models.FileField(upload_to=competition.models.writeup_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])], verbose_name='Writeup文件')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='提交时间')),
            ],
            options={
                'verbose_name': 'Writeup报告',
                'verbose_name_plural': 'Writeup报告',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WriteupTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='唯一标识符')),
                ('title', models.CharField(max_length=255, verbose_name='模板标题')),
                ('template_file', models.FileField(help_text='上传 Word 文档格式模板', upload_to='writeup/templates/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['doc', 'docx'])], verbose_name='模板文件')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': 'Writeup模板',
                'verbose_name_plural': 'Writeup模板',
                'ordering': ['-created_at'],
            },
        ),
    ]
