# Generated by Django 5.1.6 on 2025-02-26 16:18

import django.db.models.deletion
import django.utils.timezone
import imagekit.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('challenge', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScoreTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(verbose_name='队伍得分')),
                ('time', models.DateTimeField(auto_now_add=True, verbose_name='最近得分时间')),
                ('rank', models.IntegerField(default=0, verbose_name='队伍排名')),
            ],
            options={
                'verbose_name': '队伍计分',
                'verbose_name_plural': '队伍计分',
            },
        ),
        migrations.CreateModel(
            name='ScoreUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.IntegerField(default=0, verbose_name='得分')),
                ('rank', models.IntegerField(default=0, verbose_name='用户排名')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='得分时间')),
            ],
            options={
                'verbose_name': '个人计分',
                'verbose_name_plural': '个人计分',
            },
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flag', models.CharField(max_length=255, verbose_name='提交的Flag')),
                ('status', models.CharField(choices=[('correct', '正确'), ('wrong', '错误'), ('pending', '待判定')], default='pending', max_length=10, verbose_name='状态')),
                ('ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='提交IP')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='提交时间')),
                ('points_earned', models.IntegerField(default=0, verbose_name='获得分数')),
            ],
            options={
                'verbose_name': '提交记录',
                'verbose_name_plural': '提交记录',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='队伍名称')),
                ('member_count', models.IntegerField(default=4, verbose_name='队伍成员最大数量')),
            ],
            options={
                'verbose_name': '队伍',
                'verbose_name_plural': '队伍',
            },
        ),
        migrations.CreateModel(
            name='Competition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='比赛标题')),
                ('description', models.TextField(verbose_name='比赛描述')),
                ('img_link', imagekit.models.fields.ProcessedImageField(blank=True, default='public/default/default.png', help_text='上传图片大小建议使用5:3的宽高比，为了清晰度原始图片宽度应该超过250px', upload_to='competition/upload/%Y/%m/%d/', verbose_name='封面图')),
                ('start_time', models.DateTimeField(verbose_name='比赛开始时间')),
                ('end_time', models.DateTimeField(verbose_name='比赛结束时间')),
                ('is_active', models.BooleanField(default=True, verbose_name='比赛是否正在进行')),
                ('slug', models.SlugField(blank=True, null=True, unique=True, verbose_name='路由')),
                ('re_slug', models.SlugField(blank=True, null=True, unique=True, verbose_name='报名路由')),
                ('competition_type', models.CharField(choices=[('individual', '个人赛'), ('team', '团体赛')], default='team', help_text='选择比赛类型：个人赛或团体赛', max_length=10, verbose_name='比赛类型')),
                ('challenges', models.ManyToManyField(blank=True, help_text='选择与此比赛相关的题目', to='challenge.challenge', verbose_name='题目')),
            ],
            options={
                'verbose_name': '竞赛配置',
                'verbose_name_plural': '竞赛配置',
                'ordering': ['-start_time'],
            },
        ),
        migrations.CreateModel(
            name='CheatingLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cheating_type', models.CharField(choices=[('timing', 'Timing Cheating'), ('exploit', 'Exploit'), ('bot', 'Bot Activity'), ('manual', 'Manual')], max_length=50, verbose_name='作弊类型')),
                ('description', models.TextField(verbose_name='描述')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, verbose_name='记录时间')),
                ('detected_by', models.CharField(default='System', max_length=100, verbose_name='检测者')),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cheating_logs', to='competition.competition')),
            ],
            options={
                'verbose_name': '监控日志',
                'verbose_name_plural': '监控日志',
            },
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_type', models.CharField(choices=[('individual', '个人报名'), ('team', '团队报名')], default='individual', help_text='选择报名类型：个人报名或团队报名', max_length=10, verbose_name='报名类型')),
                ('student_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='学号（身份证号）')),
                ('name', models.CharField(blank=True, max_length=20, null=True, verbose_name='姓名')),
                ('role', models.CharField(blank=True, max_length=20, null=True, verbose_name='所属单位（学院）')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='联系方式')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='competition.competition', verbose_name='所属比赛')),
            ],
            options={
                'verbose_name': '报名信息',
                'verbose_name_plural': '报名信息',
            },
        ),
    ]
