# Generated by Django 5.1.6 on 2025-02-26 16:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('challenge', '0002_initial'),
        ('competition', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户ID'),
        ),
        migrations.AddField(
            model_name='scoreteam',
            name='competition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='score_team_scores', to='competition.competition'),
        ),
        migrations.AddField(
            model_name='scoreteam',
            name='solved_challenges',
            field=models.ManyToManyField(blank=True, default=None, to='challenge.challenge', verbose_name='全队已解决的挑战'),
        ),
        migrations.AddField(
            model_name='scoreuser',
            name='competition',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, related_name='score_uuser_scores', to='competition.competition', verbose_name='所属比赛'),
        ),
        migrations.AddField(
            model_name='scoreuser',
            name='solved_challenges',
            field=models.ManyToManyField(blank=True, default=None, to='challenge.challenge', verbose_name='已解决的题目'),
        ),
        migrations.AddField(
            model_name='scoreuser',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
        migrations.AddField(
            model_name='submission',
            name='challenge',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='challenge.challenge', verbose_name='题目'),
        ),
        migrations.AddField(
            model_name='submission',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='提交用户'),
        ),
        migrations.AddField(
            model_name='team',
            name='competition',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, related_name='competition_teams', to='competition.competition', verbose_name='所属比赛'),
        ),
        migrations.AddField(
            model_name='team',
            name='leader',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='led_teams', to=settings.AUTH_USER_MODEL, verbose_name='队长'),
        ),
        migrations.AddField(
            model_name='team',
            name='members',
            field=models.ManyToManyField(related_name='teams', to=settings.AUTH_USER_MODEL, verbose_name='队员'),
        ),
        migrations.AddField(
            model_name='submission',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='competition.team', verbose_name='所属队伍'),
        ),
        migrations.AddField(
            model_name='scoreuser',
            name='team',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, related_name='score_uuser_scores', to='competition.team', verbose_name='所属队伍'),
        ),
        migrations.AddField(
            model_name='scoreteam',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='score_team_scores', to='competition.team'),
        ),
        migrations.AddField(
            model_name='registration',
            name='team_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='队伍名称', to='competition.team', verbose_name='所属队伍'),
        ),
        migrations.AddField(
            model_name='cheatinglog',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cheating_logs', to='competition.team'),
        ),
        migrations.AlterUniqueTogether(
            name='team',
            unique_together={('name', 'competition')},
        ),
        migrations.AddIndex(
            model_name='submission',
            index=models.Index(fields=['challenge', 'user', 'status'], name='competition_challen_92521e_idx'),
        ),
        migrations.AddIndex(
            model_name='submission',
            index=models.Index(fields=['challenge', 'team', 'status'], name='competition_challen_e13c2f_idx'),
        ),
        migrations.AddIndex(
            model_name='submission',
            index=models.Index(fields=['created_at'], name='competition_created_fb714c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='scoreuser',
            unique_together={('team', 'user', 'competition')},
        ),
    ]
