# Generated by Django 5.1.6 on 2026-03-08 18:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('competition', '0001_initial'),
        ('container', '0001_initial'),
        ('quiz', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='作者'),
        ),
        migrations.AddField(
            model_name='challenge',
            name='docker_image',
            field=models.ForeignKey(blank=True, help_text='镜像配置（推荐使用）', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='com_challenges', to='container.dockerimage', verbose_name='镜像配置'),
        ),
        migrations.AddField(
            model_name='challenge',
            name='network_topology_config',
            field=models.ForeignKey(blank=True, help_text='选择一个预定义的网络拓扑配置，用于多场景题目', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='competition_challenges', to='container.networktopologyconfig', verbose_name='多场景题目'),
        ),
        migrations.AddField(
            model_name='challenge',
            name='static_files',
            field=models.ForeignKey(blank=True, help_text='选择要使用的静态文件（仅用于静态文件部署）', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='com_tasks_static_files', to='container.staticfile', verbose_name='静态文件'),
        ),
        migrations.AddField(
            model_name='cheatinglog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='提交用户'),
        ),
        migrations.AddField(
            model_name='combinedleaderboard',
            name='user',
            field=models.ForeignKey(blank=True, help_text='个人赛时使用', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
        migrations.AddField(
            model_name='competition',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='competition',
            name='challenges',
            field=models.ManyToManyField(blank=True, help_text='选择与此比赛相关的题目', to='competition.challenge', verbose_name='题目'),
        ),
        migrations.AddField(
            model_name='competition',
            name='related_quiz',
            field=models.OneToOneField(blank=True, help_text='一个知识竞赛只能关联一个CTF比赛。关联后将自动生成综合排行榜（CTF+知识竞赛）', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_competition', to='quiz.quiz', verbose_name='关联知识竞赛'),
        ),
        migrations.AddField(
            model_name='combinedleaderboard',
            name='competition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='combined_leaderboards', to='competition.competition', verbose_name='所属竞赛'),
        ),
        migrations.AddField(
            model_name='cheatinglog',
            name='competition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cheating_logs', to='competition.competition', verbose_name='所属比赛'),
        ),
        migrations.AddField(
            model_name='leaderboardcalculationtask',
            name='competition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leaderboard_tasks', to='competition.competition', verbose_name='所属竞赛'),
        ),
        migrations.AddField(
            model_name='registration',
            name='competition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='competition.competition', verbose_name='所属比赛'),
        ),
        migrations.AddField(
            model_name='registration',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户ID'),
        ),
        migrations.AddField(
            model_name='scoreteam',
            name='competition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='score_team_scores', to='competition.competition', verbose_name='所属比赛'),
        ),
        migrations.AddField(
            model_name='scoreteam',
            name='solved_challenges',
            field=models.ManyToManyField(blank=True, default=None, to='competition.challenge', verbose_name='全队已解决的挑战'),
        ),
        migrations.AddField(
            model_name='scoreuser',
            name='competition',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, related_name='score_uuser_scores', to='competition.competition', verbose_name='所属比赛'),
        ),
        migrations.AddField(
            model_name='scoreuser',
            name='solved_challenges',
            field=models.ManyToManyField(blank=True, default=None, to='competition.challenge', verbose_name='已解决的题目'),
        ),
        migrations.AddField(
            model_name='scoreuser',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
        migrations.AddField(
            model_name='submission',
            name='challenge',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='competition.challenge', verbose_name='题目'),
        ),
        migrations.AddField(
            model_name='submission',
            name='competition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='competition.competition', verbose_name='所属比赛'),
        ),
        migrations.AddField(
            model_name='submission',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='提交用户'),
        ),
        migrations.AddField(
            model_name='challenge',
            name='tags',
            field=models.ManyToManyField(blank=True, to='competition.tag', verbose_name='标签'),
        ),
        migrations.AddField(
            model_name='team',
            name='competition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competition_teams', to='competition.competition', verbose_name='所属比赛'),
        ),
        migrations.AddField(
            model_name='team',
            name='leader',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='led_teams', to=settings.AUTH_USER_MODEL, verbose_name='队长'),
        ),
        migrations.AddField(
            model_name='team',
            name='members',
            field=models.ManyToManyField(related_name='teams', to=settings.AUTH_USER_MODEL, verbose_name='队员'),
        ),
        migrations.AddField(
            model_name='submission',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='competition.team', verbose_name='所属队伍'),
        ),
        migrations.AddField(
            model_name='scoreuser',
            name='team',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='score_uuser_scores', to='competition.team', verbose_name='所属队伍'),
        ),
        migrations.AddField(
            model_name='scoreteam',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='score_team_scores', to='competition.team', verbose_name='所属队伍'),
        ),
        migrations.AddField(
            model_name='registration',
            name='team_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='队伍名称', to='competition.team', verbose_name='所属队伍'),
        ),
        migrations.AddField(
            model_name='combinedleaderboard',
            name='team',
            field=models.ForeignKey(blank=True, help_text='团队赛时使用', null=True, on_delete=django.db.models.deletion.CASCADE, to='competition.team', verbose_name='队伍'),
        ),
        migrations.AddField(
            model_name='cheatinglog',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cheating_logs', to='competition.team', verbose_name='所属队伍'),
        ),
        migrations.AddField(
            model_name='writeup',
            name='competition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='writeups', to='competition.competition', verbose_name='所属比赛'),
        ),
        migrations.AddField(
            model_name='writeup',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='writeups', to='competition.team', verbose_name='所属队伍'),
        ),
        migrations.AddField(
            model_name='writeup',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='writeups', to=settings.AUTH_USER_MODEL, verbose_name='提交者'),
        ),
        migrations.AddField(
            model_name='writeuptemplate',
            name='competition',
            field=models.ForeignKey(blank=True, help_text='留空表示通用模板', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='writeup_templates', to='competition.competition', verbose_name='所属比赛'),
        ),
        migrations.AddIndex(
            model_name='leaderboardcalculationtask',
            index=models.Index(fields=['competition', 'status'], name='competition_competi_12cd2c_idx'),
        ),
        migrations.AddIndex(
            model_name='leaderboardcalculationtask',
            index=models.Index(fields=['competition', '-created_at'], name='competition_competi_fd8065_idx'),
        ),
        migrations.AddIndex(
            model_name='challenge',
            index=models.Index(fields=['uuid'], name='idx_chal_uuid'),
        ),
        migrations.AddIndex(
            model_name='challenge',
            index=models.Index(fields=['difficulty', 'points'], name='idx_chal_diff_pts'),
        ),
        migrations.AddIndex(
            model_name='challenge',
            index=models.Index(fields=['category', 'is_active'], name='idx_chal_cat_active'),
        ),
        migrations.AddIndex(
            model_name='challenge',
            index=models.Index(fields=['solves'], name='idx_chal_solves'),
        ),
        migrations.AlterUniqueTogether(
            name='team',
            unique_together={('name', 'competition')},
        ),
        migrations.AddIndex(
            model_name='submission',
            index=models.Index(fields=['challenge', 'user', 'status'], name='competition_challen_92521e_idx'),
        ),
        migrations.AddIndex(
            model_name='submission',
            index=models.Index(fields=['challenge', 'team', 'status'], name='competition_challen_e13c2f_idx'),
        ),
        migrations.AddIndex(
            model_name='submission',
            index=models.Index(fields=['created_at'], name='competition_created_fb714c_idx'),
        ),
        migrations.AddIndex(
            model_name='submission',
            index=models.Index(fields=['competition'], name='competition_competi_cfec8e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='scoreuser',
            unique_together={('team', 'user', 'competition')},
        ),
        migrations.AddIndex(
            model_name='combinedleaderboard',
            index=models.Index(fields=['competition', 'rank'], name='competition_competi_c44c71_idx'),
        ),
        migrations.AddIndex(
            model_name='combinedleaderboard',
            index=models.Index(fields=['competition', '-combined_score'], name='competition_competi_8f319b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='combinedleaderboard',
            unique_together={('competition', 'team'), ('competition', 'user')},
        ),
        migrations.AddIndex(
            model_name='writeup',
            index=models.Index(fields=['competition', '-created_at'], name='competition_competi_d30627_idx'),
        ),
    ]
