# Generated by Django 5.1.6 on 2025-02-28 12:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0004_remove_challenge_docker_images_and_more'),
        ('competition', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scoreuser',
            name='solved_challenges',
            field=models.ManyToManyField(blank=True, default=None, null=True, to='challenge.challenge', verbose_name='已解决的题目'),
        ),
        migrations.AlterField(
            model_name='scoreuser',
            name='team',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='score_uuser_scores', to='competition.team', verbose_name='所属队伍'),
        ),
    ]
