# Generated by Django 5.1.6 on 2025-02-28 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0004_remove_challenge_docker_images_and_more'),
        ('competition', '0003_alter_scoreuser_solved_challenges_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scoreuser',
            name='solved_challenges',
            field=models.ManyToManyField(blank=True, default=None, to='challenge.challenge', verbose_name='已解决的题目'),
        ),
    ]
