# Generated by Django 5.1.6 on 2025-03-05 16:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0004_remove_challenge_docker_images_and_more'),
        ('competition', '0004_alter_scoreuser_solved_challenges'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='competition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='competition.competition', verbose_name='所属比赛'),
        ),
        migrations.AddIndex(
            model_name='submission',
            index=models.Index(fields=['competition'], name='competition_competi_cfec8e_idx'),
        ),
    ]
