"""
Django settings for snowctf project.

Generated by 'django-admin startproject' using Django 5.1.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
import os
import sys
import warnings


BASE_DIR = Path(__file__).resolve().parent.parent

sys.path.insert(0, os.path.join(BASE_DIR, 'apps'))


RUNNING_DB_MIGRATION = any(cmd in sys.argv for cmd in [
    'migrate', 'makemigrations', 'showmigrations', 'sqlmigrate',
    'squashmigrations', 'inspectdb', 'flush', 'createsuperuser'
])


warnings.filterwarnings(
    'ignore',
    message='Accessing the database during app initialization is discouraged',
    category=RuntimeWarning,
    module='django.db.backends.utils'
)


SECRET_KEY = os.getenv('SNOW_SECRET_KEY', 'django-insecure-)+vh#@l4crslu5fza1e8da!2(0s10mw5%_1=*uko7cu9ju*yv-')


ENCRYPTION_KEY = os.getenv('ENCRYPTION_KEY', 'SecSnowEncryptKey2024567890AB')


DEBUG = os.getenv('SNOW_DEBUG', 'True').upper() == 'TRUE'

if DEBUG:
    ALLOWED_HOSTS = ['*']
else:
    
    allowed_hosts_env = os.getenv('SNOW_ALLOWED_HOSTS', '')
    if allowed_hosts_env == '*':
        ALLOWED_HOSTS = ['*']
    else:
        ALLOWED_HOSTS = [host.strip() for host in allowed_hosts_env.split(',') if host.strip()]
        
       
        internal_hosts = ['_', 'rustfs', 'localhost', '127.0.0.1']
        for internal_host in internal_hosts:
            if internal_host not in ALLOWED_HOSTS:
                ALLOWED_HOSTS.append(internal_host)


if not DEBUG:
   
    csrf_origins_env = os.getenv('SNOW_CSRF_TRUSTED_ORIGINS', '')
    if csrf_origins_env:
        
        CSRF_TRUSTED_ORIGINS = [origin.strip() for origin in csrf_origins_env.split(',') if origin.strip()]
    else:
        
        CSRF_TRUSTED_ORIGINS = []
        for host in ALLOWED_HOSTS:
            if host != '*':
               
                CSRF_TRUSTED_ORIGINS.extend([
                    f'https://{host}',
                    f'http://{host}',
                ])
else:
  
    CSRF_TRUSTED_ORIGINS = ['http://localhost:8000', 'http://127.0.0.1:8000']



LOGIN_REDIRECT_URL = "/"

# Email setting
# 邮箱验证方式：none(不验证) / optional(可选) / mandatory(强制)
# 通过环境变量 SNOW_ACCOUNT_EMAIL_VERIFICATION 配置
# 注意：必须在后台启用邮箱功能，此设置才会生效
ACCOUNT_EMAIL_VERIFICATION = os.getenv('SNOW_ACCOUNT_EMAIL_VERIFICATION', 'none').lower()

# django-allauth 新版本配置方式
ACCOUNT_SIGNUP_FIELDS = ['email*', 'username*', 'password1*', 'password2*']  # * 表示必填
ACCOUNT_UNIQUE_EMAIL = True  # 邮箱唯一
ACCOUNT_DEFAULT_HTTP_PROTOCOL = os.getenv('SNOW_PROTOCOL_HTTPS', 'HTTP').lower()

# 密码重置token有效期（秒）默认3天
PASSWORD_RESET_TIMEOUT = 60 * 60  # 1小时



ACCOUNT_LOGIN_METHODS = {'email', 'username'}
# 禁止社交账号自动注册
SOCIALACCOUNT_AUTO_SIGNUP = False

SOCIALACCOUNT_FORMS = {
    'signup': 'allauth.socialaccount.forms.SignupForm',
}

SITE_CREATE_DATE = os.getenv('SNOW_SITE_CREATE_DATE', '2024-01-01')
# 个人 Github 地址
MY_GITHUB = os.getenv('SNOW_GITHUB', '')
# 是否开启 SSE 功能
SEO_FLAG = os.getenv('SNOW_SEO_FLAG', 'False').upper() == 'TRUE'
# 工信部备案信息
BEIAN = os.getenv('SNOW_BEIAN', 'ICP备XXXXXXXXXXXX号-1')
# 站长统计（友盟）
CNZZ_PROTOCOL = os.getenv('SNOW_CNZZ_PROTOCOL', '')
# 站长统计（51.la）
LA51_PROTOCOL = os.getenv('SNOW_LA51_PROTOCOL', '')
# 站长推送
MY_SITE_VERIFICATION = os.getenv('SNOW_SITE_VERIFICATION', '')
# 使用 http 还是 https （sitemap 中的链接可以体现出来）
# 个人外链信息（导航栏下拉中显示）
PRIVATE_LINKS = os.getenv('SNOW_PRIVATE_LINKS', '[]')

INSTALLED_APPS = [
    'simpleui', #后台美化
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'django.contrib.sites',
    'django.contrib.sitemaps',  # 必需notice
    'django.contrib.humanize',
    
    # allauth 相关应用
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.weibo',
    'allauth.socialaccount.providers.github',
    'captcha',

    # 对象存储
    'storages', 

    # Celery 相关（必须在 easytask 之前，确保先注册）
    'celery_config.apps.CustomCeleryResultConfig',  # Celery 任务结果（自定义中文名）
    'django_celery_beat',  # Celery Beat 定时任务（官方包）


    'comment',
    'competition',
    'container',
    'easytask.apps.EasytaskConfig',  # 必须在 celery_config 之后，才能取消注册并重新注册 Admin
    'oauth',
    'public',
    'logs',
    'blog',
    'practice',
    'rsshub',
    'tool',
    'recruit',
    'quiz',

   
    #自定义app结束

    'imagekit', #上传图片应用

    'crispy_forms',
    'crispy_bootstrap4',
    'haystack',
    
]

AUTHENTICATION_BACKENDS = (
    # Needed to login by username in Django admin, regardless of `allauth`
    'django.contrib.auth.backends.ModelBackend',

    # `allauth` specific authentication methods, such as login by e-mail
    'allauth.account.auth_backends.AuthenticationBackend',
)


MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',

    'allauth.account.middleware.AccountMiddleware',
    'apps.public.middleware.APIPermissionMiddleware',
    'apps.public.middleware.MemberCheckMiddleware',
    
    # 数据库连接管理中间件（防止连接泄漏 - 必须放在最后）
    'apps.competition.db_middleware.DatabaseConnectionMiddleware',
]


CAPTCHA_LENGTH = 4  # 验证码长度
CAPTCHA_TIMEOUT = 5  # 验证码过期时间（分钟）
CAPTCHA_NOISE_FUNCTIONS = ('captcha.helpers.noise_dots',)  # 噪点样式
CAPTCHA_CHALLENGE_FUNCT = 'captcha.helpers.random_char_challenge'  # 验证码生成函数
CRISPY_ALLOWED_TEMPLATE_PACKS = "bootstrap4"
CRISPY_TEMPLATE_PACK = "bootstrap4"

ROOT_URLCONF = 'secsnow.urls'

LANGUAGE_CODE = 'zh-hans'

TIME_ZONE = 'Asia/Shanghai'

USE_TZ = False

ACCOUNT_FORMS = {
    'login': 'oauth.forms.CustomLoginForm',
    'signup': 'oauth.forms.CustomSignupForm',
    'add_email': 'oauth.forms.CustomAddEmailForm',
}

# 自定义适配器 - 用于控制注册功能开关
ACCOUNT_ADAPTER = 'oauth.adapter.CustomAccountAdapter'
SOCIALACCOUNT_ADAPTER = 'oauth.adapter.CustomSocialAccountAdapter'

CELERY_ADJUST_TIMEZONE = os.getenv('CELERY_ADJUST_TIMEZONE', 'True').upper() == 'TRUE'


# 下载令牌有效期（秒）
DOWNLOAD_TOKEN_MAX_AGE = int(os.getenv('DOWNLOAD_TOKEN_MAX_AGE', '300'))  # 5分钟

# 文件级频率限制
DOWNLOAD_RATE_WINDOW = int(os.getenv('DOWNLOAD_RATE_WINDOW', '60'))     # 1分钟
DOWNLOAD_RATE_LIMIT = int(os.getenv('DOWNLOAD_RATE_LIMIT', '5'))       # 最多5次

# 用户全局频率限制
DOWNLOAD_GLOBAL_RATE_WINDOW = int(os.getenv('DOWNLOAD_GLOBAL_RATE_WINDOW', '3600'))  # 1小时
DOWNLOAD_GLOBAL_RATE_LIMIT = int(os.getenv('DOWNLOAD_GLOBAL_RATE_LIMIT', '100'))    # 最多100次

SNOWAI_ENABLE_HYBRID_SEARCH = os.getenv('SNOWAI_ENABLE_HYBRID_SEARCH', 'true').lower() == 'true'
# BM25 权重0-1 之间，默认0.3
SNOWAI_BM25_WEIGHT = float(os.getenv('SNOWAI_BM25_WEIGHT', '0.3'))
# 向量检索权重（0-1 之间，建议 0.6-0.7）
SNOWAI_VECTOR_WEIGHT = float(os.getenv('SNOWAI_VECTOR_WEIGHT', '0.7'))
# 向量模型名称
SNOWAI_EMBEDDING_MODEL = os.getenv('SNOWAI_EMBEDDING_MODEL', 'shibing624/text2vec-base-chinese')
# HuggingFace 镜像地址（国内用户加速下载）
HF_ENDPOINT = os.getenv('HF_ENDPOINT', 'https://hf-mirror.com')




TOOL_FLAG = os.getenv('SNOW_TOOL_FLAG', 'True').upper() == 'TRUE'
# 是否开启[API]应用
API_FLAG = os.getenv('SNOW_API_FLAG', 'False').upper() == 'TRUE'

# ── 模块功能开关 ──────────────────────────────────────────────────────────
# 每个开关同时控制：导航栏入口显示 + 对应搜索类型选项
# 在 .env 中配置，True=启用，False=隐藏
MODULE_COMPETITION  = os.getenv('SNOW_MODULE_COMPETITION',  'True').upper() == 'TRUE'   # 竞赛中心
MODULE_PRACTICE     = os.getenv('SNOW_MODULE_PRACTICE',     'True').upper() == 'TRUE'   # 漏洞靶场
MODULE_QUIZ         = os.getenv('SNOW_MODULE_QUIZ',         'True').upper() == 'TRUE'   # 知识竞赛
MODULE_BLOG         = os.getenv('SNOW_MODULE_BLOG',         'True').upper() == 'TRUE'   # WIKI空间
MODULE_TOOL         = os.getenv('SNOW_MODULE_TOOL',         'True').upper() == 'TRUE'   # 在线工具（同步覆盖原 TOOL_FLAG）
MODULE_RECRUIT      = os.getenv('SNOW_MODULE_RECRUIT',      'True').upper() == 'TRUE'   # 安全岗位
MODULE_REWARD       = os.getenv('SNOW_MODULE_REWARD',       'True').upper() == 'TRUE'   # 兑奖中心
#SITE_ID = int(os.getenv('SITE_ID', '1'))
SITE_ID = int(os.getenv('SITE_ID', '5'))


TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',

                'public.context_processors.settings_info',
            ],
        },
    },
]

WSGI_APPLICATION = 'secsnow.wsgi.application'

AUTH_USER_MODEL = 'oauth.Ouser'

# *************************************** 静态文件配置开始 ***************************************
# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.10/howto/static-files/

# 静态文件收集
STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'static')

# 媒体文件收集 - 支持对象存储（RustFS 或其他 S3 兼容存储）
USE_OBJECT_STORAGE = os.getenv('SNOW_USE_OBJECT_STORAGE', 'False').lower() == 'true'

if USE_OBJECT_STORAGE:
    # 使用对象存储（RustFS - S3 兼容）
    # Django 4.2+ 新的 STORAGES 配置方式
    STORAGES = {
        "default": {
            # 使用自定义存储后端，解决 Docker 内部地址无法访问的问题
            "BACKEND": "secsnow.storage_backends.MediaStorage",
        },
        "staticfiles": {
            "BACKEND": "django.contrib.staticfiles.storage.StaticFilesStorage",
        },
    }
    
    # 对象存储配置（兼容 S3 API）
    AWS_ACCESS_KEY_ID = os.getenv('SNOW_STORAGE_ACCESS_KEY', '')
    AWS_SECRET_ACCESS_KEY = os.getenv('SNOW_STORAGE_SECRET_KEY', '')
    AWS_STORAGE_BUCKET_NAME = os.getenv('SNOW_STORAGE_BUCKET_NAME', '')
    
    # AWS_S3_ENDPOINT_URL 是 boto3 内部连接对象存储的地址
    # 默认使用 Docker 内部地址（不对外暴露），通过 Nginx 代理访问
    # 注意：不要在 URL 中包含 bucket 名称！
    AWS_S3_ENDPOINT_URL = os.getenv('SNOW_STORAGE_ENDPOINT_URL', '')
    
    # AWS_LOCATION: 文件在 bucket 中的路径前缀（留空表示存储在 bucket 根目录）
    # 如果设置为 'media'，文件会存储在 s3://secsnow/media/uploads/file.jpg
    # 当前留空，文件存储在 s3://secsnow/uploads/file.jpg
    AWS_LOCATION = os.getenv('SNOW_STORAGE_LOCATION', '')
    
    AWS_S3_REGION_NAME = os.getenv('SNOW_STORAGE_REGION', 'us-east-1')
    AWS_S3_USE_SSL = os.getenv('SNOW_STORAGE_USE_SSL', 'False').lower() == 'true'
    AWS_S3_VERIFY = os.getenv('SNOW_STORAGE_VERIFY_SSL', 'False').lower() == 'true'
    AWS_DEFAULT_ACL = None
    AWS_S3_OBJECT_PARAMETERS = {
        'CacheControl': 'max-age=86400',
    }
    AWS_QUERYSTRING_AUTH = False  # 公开访问
    AWS_S3_FILE_OVERWRITE = False  # 不覆盖同名文件
    
    # 禁用服务器端加密（解决 KMS 未初始化的问题）
    AWS_S3_ENCRYPTION = False  # 不使用服务器端加密
    # 不设置加密相关参数，避免触发 KMS 服务
    # AWS_S3_KMS_KEY_ID 不设置
    # AWS_S3_SSE_CUSTOMER_KEY 不设置
    
    # S3 配置优化：使用 path-style 访问，避免 DNS 查询问题
    AWS_S3_ADDRESSING_STYLE = 'path'  # 使用 path-style: http://endpoint/bucket/key
    AWS_S3_SIGNATURE_VERSION = 's3v4'  # 使用 V4 签名
    
    # 根据 AWS_S3_USE_SSL 设置 URL 协议
    # boto3 默认使用 HTTPS，如果不使用 SSL，需要明确指定
    if not AWS_S3_USE_SSL:
        AWS_S3_URL_PROTOCOL = 'http:'  # 强制使用 HTTP 协议生成 URL
    
    
    storage_public_url = os.getenv('SNOW_STORAGE_PUBLIC_URL', '')
    endpoint_url = AWS_S3_ENDPOINT_URL
    
    # 检测是否为 Docker 内部地址
    is_internal = any(keyword in endpoint_url for keyword in ['rustfs', 'localhost', '127.0.0.1'])
    
    if storage_public_url:
        # 方案1：使用自定义公网访问地址（推荐用于生产环境暴露服务）
        # 例如：SNOW_STORAGE_PUBLIC_URL=http://你的公网IP:7900
        from urllib.parse import urlparse
        parsed = urlparse(storage_public_url)
        
        # 构建自定义域名（包含 bucket）
        if parsed.path.strip('/') == AWS_STORAGE_BUCKET_NAME:
            # URL 已包含 bucket：http://ip:port/bucket
            custom_domain = f"{parsed.netloc}/{AWS_STORAGE_BUCKET_NAME}"
        else:
            # URL 不包含 bucket：http://ip:port
            custom_domain = f"{parsed.netloc}/{AWS_STORAGE_BUCKET_NAME}"
        
        AWS_S3_CUSTOM_DOMAIN = custom_domain
        protocol = parsed.scheme or 'http'
        MEDIA_URL = f'{protocol}://{custom_domain}/'
        
    elif is_internal:
        AWS_S3_CUSTOM_DOMAIN = None
        MEDIA_URL = '/media/'
        
    else:
        # 方案3：外部对象存储地址（直接访问）
        # 适用于使用外网 IP 或第三方对象存储服务
        AWS_S3_CUSTOM_DOMAIN = None
        MEDIA_URL = f'{endpoint_url}/{AWS_STORAGE_BUCKET_NAME}/'
else:
    # 使用本地文件系统
    STORAGES = {
        "default": {
            "BACKEND": "django.core.files.storage.FileSystemStorage",
        },
        "staticfiles": {
            "BACKEND": "django.contrib.staticfiles.storage.StaticFilesStorage",
        },
    }
    MEDIA_URL = '/media/'
    MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
# *************************************** 静态文件配置结束 ***************************************

# *************************************** 数据库配置开始 ***************************************
# 配置数据库（PostgreSQL）
snow_postgres_host = os.getenv('SNOW_POSTGRES_HOST', '127.0.0.1')
snow_postgres_name = os.getenv('SNOW_POSTGRES_NAME', 'sstf')
snow_postgres_user = os.getenv('SNOW_POSTGRES_USER', 'postgres')
snow_postgres_pwd = os.getenv('SNOW_POSTGRES_PASSWORD', 'G5ZjwAzeEHAa6fyx')
snow_postgres_port = os.getenv('SNOW_POSTGRES_PORT', 5432)

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',  # 使用 PostgreSQL 数据库
        'NAME': snow_postgres_name,  # 数据库的名称
        'USER': snow_postgres_user,  # 数据库的用户名
        'PASSWORD': snow_postgres_pwd,  # 数据库的密码
        'HOST': snow_postgres_host,
        'PORT': snow_postgres_port,
        'OPTIONS': {
            'connect_timeout': 10,  #  连接超时 10秒（30 → 10）
            'options': '-c timezone=Asia/Shanghai',  # 时区设置（statement_timeout 不兼容 PgBouncer）
            # PostgreSQL 连接池优化参数
            'keepalives': 1,  # 启用TCP keepalive
            'keepalives_idle': 30,  # 空闲30秒后发送keepalive
            'keepalives_interval': 10,  # keepalive间隔10秒
            'keepalives_count': 5,  # keepalive重试5次
        },

        'CONN_MAX_AGE': 600,  

        'ATOMIC_REQUESTS': False,
        'DISABLE_SERVER_SIDE_CURSORS': True,  # ← 添加逗号修复语法错误
 
    }
}
# *************************************** 数据库配置结束 **************************************


# *************************************** 缓存配置开始 ***************************************
# 使用django-redis缓存页面，缓存配置如下：
snow_redis_host = os.getenv('SNOW_REDIS_HOST', '127.0.0.1')
snow_redis_port = os.getenv('SNOW_REDIS_PORT', 6379)
snow_redis_password = os.getenv('SNOW_REDIS_PASSWORD', '')

# 构建 Redis URL（支持密码）
if snow_redis_password:
    redis_cache_url = "redis://:{}@{}:{}/0".format(snow_redis_password, snow_redis_host, snow_redis_port)
    redis_celery_url = "redis://:{}@{}:{}/1".format(snow_redis_password, snow_redis_host, snow_redis_port)
else:
    redis_cache_url = "redis://{}:{}/0".format(snow_redis_host, snow_redis_port)
    redis_celery_url = "redis://{}:{}/1".format(snow_redis_host, snow_redis_port)

CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": redis_cache_url,
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
            "CONNECTION_POOL_KWARGS": {
                "max_connections": 50,
                "retry_on_timeout": True,
                "socket_keepalive": True,
                "health_check_interval": 30,
            },
          
            "SOCKET_CONNECT_TIMEOUT": 5,       
            "SOCKET_TIMEOUT": 5,                
           
            "COMPRESSOR": "django_redis.compressors.zlib.ZlibCompressor", 
            "IGNORE_EXCEPTIONS": True,         
        }
    }
}
# *************************************** 缓存配置结束 ***************************************

# *************************************** 搜索 ***************************************
HAYSTACK_CONNECTIONS = {
       'default': {
           'ENGINE': 'blog.whoosh_cn_backend.WhooshEngine',  # 使用中文分词后端
           'PATH': os.path.join(BASE_DIR, 'whoosh_index'),  # Whoosh 索引路径
       },
   }
# 搜索配置
HAYSTACK_SEARCH_RESULTS_PER_PAGE = 12  # 每页显示结果数
HAYSTACK_SIGNAL_PROCESSOR = 'haystack.signals.RealtimeSignalProcessor'  # 实时更新索引
# *************************************** 搜索 ***************************************




# *************************************** celery 配置开始 ***************************************
# 跟缓存的redis配置类似，使用不同的库就行
CELERY_BROKER_URL = redis_celery_url
# 时区跟Django的一致
CELERY_TIMEZONE = TIME_ZONE
CELERY_ENABLE_UTC = False  # 不使用 UTC
# 注意：django-celery-beat 需要 Django USE_TZ=True 才能正常工作

# 支持数据库django-db和缓存django-cache存储任务状态及结果
CELERY_RESULT_BACKEND = "django-db"
CELERY_CACHE_BACKEND = 'django-cache'
# 使用 django-celery-beat 官方调度器（从数据库读取配置）
CELERY_BEAT_SCHEDULER = 'django_celery_beat.schedulers:DatabaseScheduler'
# Beat状态文件存储路径（自动在当前目录创建）
# celery内容等消息的格式设置，默认json
CELERY_ACCEPT_CONTENT = ['application/json', ]
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
# 每个 worker 最多执行n个任务就会被销毁，可防止内存泄露和数据库连接泄露
CELERY_WORKER_MAX_TASKS_PER_CHILD = 100

#  【关键配置】修改 Celery 默认队列名（从 'celery' 改为 'default'）
# 原因：Celery 内置默认队列名是 'celery'，但我们的 Worker 监听的是 'default' 队列
# 如果不设置这个，Django Admin 手动运行的任务会进入 'celery' 队列，导致没有 Worker 处理
CELERY_TASK_DEFAULT_QUEUE = 'default'
CELERY_TASK_DEFAULT_EXCHANGE = 'default'
CELERY_TASK_DEFAULT_ROUTING_KEY = 'default'

#  数据库连接管理优化（防止 connection already closed 错误）
# Worker 预取任务数量（全局默认值，各 Worker 可在启动命令中覆盖）
# 注意：
#   - prefetch_count = 并发数 × PREFETCH_MULTIPLIER
#   - 默认模式：单 Worker (gevent 50并发) → prefetch=50 (50×1)
#   - 高性能模式：
#     * 容器 Worker (gevent 150并发) → prefetch=300 (150×2, 在命令行覆盖)
#     * 通用 Worker (prefork 6并发) → prefetch=6 (6×1, 在命令行覆盖)
CELERY_WORKER_PREFETCH_MULTIPLIER = 1  # 全局默认值

# 禁用连接池（让每个任务使用独立的连接）
#  Celery Broker 连接池优化（2核4G优化：降低连接数避免 Redis 连接耗尽）
CELERY_BROKER_POOL_LIMIT = 30  # 限制每个 Worker 的连接数（50 → 20）
CELERY_BROKER_CONNECTION_MAX_RETRIES = 10  # 最大重试次数
CELERY_BROKER_CONNECTION_RETRY_ON_STARTUP = True

# 任务优先级配置（0-9，数字越大优先级越高）
CELERY_TASK_ACKS_ON_FAILURE_OR_TIMEOUT = True  # 任务失败或超时也确认，避免重复执行
CELERY_TASK_REJECT_ON_WORKER_LOST = True  # Worker 丢失时拒绝任务
CELERY_WORKER_DISABLE_RATE_LIMITS = False  # 启用速率限制（防止任务风暴）

# 为存储结果设置过期日期，默认1天过期。如果beat开启，Celery每天会自动清除，0表示永不清理
# 这里可以设置成0，然后自己创建清理结果的机制，比较好控制
CELERY_RESULT_EXPIRES = 0
CELERY_BROKER_CONNECTION_RETRY = True

# 心跳配置（解决 Worker 心跳丢失问题）
CELERY_BROKER_HEARTBEAT = 60  # Broker 心跳间隔：60秒（默认120秒，增加心跳频率）
CELERY_BROKER_HEARTBEAT_CHECKRATE = 2  # 心跳检查频率：每2秒检查一次
CELERY_EVENT_QUEUE_EXPIRES = 60  # 事件队列过期时间：60秒
CELERY_WORKER_SEND_TASK_EVENTS = False  # 关闭任务事件发送（减少 Redis 写入）

# 关键配置：任务确认和状态追踪
CELERY_TASK_ACKS_LATE = True  # 任务执行后才确认，revoke 才能生效
CELERY_TASK_TRACK_STARTED = False  # 关闭任务状态追踪（减少 Redis 写入，提升性能）

# 任务超时配置（防止任务卡死占用 worker）
# 注意：
#   - 快速任务（容器创建）：1-2分钟足够
#   - 慢速任务（批量清理）：可能需要 10-30 分钟
#   - expires_seconds 应该 > time_limit，否则任务可能执行到一半被撤销
CELERY_TASK_TIME_LIMIT = 1800  # 硬超时：30分钟（给慢任务足够时间）
CELERY_TASK_SOFT_TIME_LIMIT = 1740  # 软超时：29分钟（提前1分钟警告）
# 任务路由配置（将不同类型的任务分配到不同队列）
#  注意：如果任务使用了 @shared_task(name='xxx')，这里必须使用 'xxx' 而不是函数路
CELERY_TASK_ROUTES = {
    # ==================== 容器管理任务 ====================
    'easytask.tasks.cleanup_expired_containers_bucket': {
        'queue': 'container_cleanup',
        'routing_key': 'container.cleanup',
    },
    'easytask.tasks.cleanup_expired_containers': {
        'queue': 'container_cleanup',
        'routing_key': 'container.cleanup',
    },
    'easytask.tasks.cleanup_container': {
        'queue': 'container_cleanup',
        'routing_key': 'container.cleanup',
    },
    'easytask.tasks.flag_destroy_web_container': {
        'queue': 'container_cleanup',
        'routing_key': 'container.cleanup',
    },
    'easytask.tasks.check_docker_engines_health': {
        'queue': 'default',
        'routing_key': 'container.health',
    },
    
    # ==================== 容器创建任务（竞赛模块）====================
    'competition.tasks.create_container_async': {
        'queue': 'container_creation',
        'routing_key': 'container.create',
    },
    'competition.tasks.update_competition_rankings': {
        'queue': 'default',
        'routing_key': 'rankings.update',
    },
    'competition.tasks.cleanup_failed_and_pending_pods': {
        'queue': 'maintenance',
        'routing_key': 'k8s.cleanup.pods',
    },
    'competition.tasks.batch_cleanup_expired_containers': {
        'queue': 'maintenance',
        'routing_key': 'maintenance.cleanup',
    },
    'competition.tasks.cleanup_pending_tasks': {
        'queue': 'maintenance',
        'routing_key': 'maintenance.pending',
    },
    
    # ==================== 容器创建任务（练习模块）====================
    'practice.tasks.create_container_async': {
        'queue': 'container_creation',
        'routing_key': 'container.create.practice',
    },
    'practice.tasks.batch_cleanup_expired_containers': {
        'queue': 'maintenance',
        'routing_key': 'maintenance.cleanup.practice',
    },
    'practice.tasks.cleanup_pending_tasks': {
        'queue': 'maintenance',
        'routing_key': 'maintenance.pending.practice',
    },
    
    # ==================== 镜像管理任务 ====================
    'easytask.tasks.pull_docker_image': {
        'queue': 'default',
        'routing_key': 'image.pull',
    },
    'easytask.tasks.pull_multiple_docker_images': {
        'queue': 'default',
        'routing_key': 'image.pull.batch',
    },
    'easytask.tasks.batch_check_images_status': {
        'queue': 'default',
        'routing_key': 'image.status',
    },
    
    # ==================== 知识库同步任务 ====================
    'easytask.tasks.sync_wiki_knowledge_base': {
        'queue': 'maintenance',
        'routing_key': 'knowledge.wiki',
    },
    'easytask.tasks.sync_external_knowledge_sources': {
        'queue': 'maintenance',
        'routing_key': 'knowledge.external',
    },
    'easytask.tasks.sync_ctf_writeups': {
        'queue': 'maintenance',
        'routing_key': 'knowledge.ctf',
    },
    
    # ==================== 通知任务 ====================
    'easytask.tasks.send_unread_notifications_email': {
        'queue': 'default',
        'routing_key': 'notification.email',
    },
    
    # ==================== 比赛排行榜任务 ====================
    'easytask.tasks.save_combined_leaderboard_to_db': {
        'queue': 'default',
        'routing_key': 'competition.leaderboard',
    },
    'easytask.tasks.auto_calculate_ended_competitions': {
        'queue': 'default',
        'routing_key': 'competition.calculate',
    },
    
    # ==================== 系统维护任务 ====================
    'easytask.tasks.clear_all_caches': {
        'queue': 'maintenance',
        'routing_key': 'maintenance.cache',
    },
    'easytask.tasks.clear_notification': {
        'queue': 'maintenance',
        'routing_key': 'maintenance.notification',
    },
    'easytask.tasks.cleanup_task_result': {
        'queue': 'maintenance',
        'routing_key': 'maintenance.task_result',
    },
    'easytask.tasks.clear_expired_sessions': {
        'queue': 'maintenance',
        'routing_key': 'maintenance.session',
    },
    
    # ==================== K8s 相关任务 ====================
    'easytask.tasks.cleanup_k8s_stale_pods': {
        'queue': 'maintenance',
        'routing_key': 'k8s.cleanup',
    },
    'easytask.tasks.optimize_k8s_resources': {
        'queue': 'maintenance',
        'routing_key': 'k8s.optimize',
    },
}

#  任务优先级配置（0-9，9最高）
CELERY_TASK_DEFAULT_PRIORITY = 5
CELERY_TASK_QUEUE_MAX_PRIORITY = 10

#  任务级别的详细配置（限流、超时等）
CELERY_TASK_ANNOTATIONS = {
    # ==================== 容器创建任务 ====================
    'competition.tasks.create_container_async': {
        'rate_limit': '150/m',  # 每分钟最多150个容器创建任务（匹配 gevent 并发数）
        'time_limit': 300,
        'soft_time_limit': 240,
        'priority': 8,  # 最高优先级（比赛）
    },
    'practice.tasks.create_container_async': {
        'rate_limit': '150/m',  # 与比赛共享限流
        'time_limit': 300,
        'soft_time_limit': 240,
        'priority': 7,  # 稍低于比赛
    },
    
    # ==================== 容器清理任务 ====================
    'easytask.tasks.cleanup_expired_containers_bucket': {
        'rate_limit': '200/m',
        'time_limit': 120,
        'soft_time_limit': 100,
        'priority': 6,
        'expires': 60,  # 1分钟过期（高频任务）
    },
    'easytask.tasks.cleanup_expired_containers': {
        'time_limit': 300,
        'soft_time_limit': 270,
        'priority': 5,
    },
    'easytask.tasks.cleanup_container': {
        'rate_limit': '200/m',
        'time_limit': 60,
        'soft_time_limit': 50,
        'priority': 6,
    },
    'easytask.tasks.flag_destroy_web_container': {
        'time_limit': 60,
        'soft_time_limit': 50,
        'priority': 7,
    },
    'competition.tasks.batch_cleanup_expired_containers': {
        'time_limit': 600,
        'soft_time_limit': 540,
        'priority': 3,
    },
    'practice.tasks.batch_cleanup_expired_containers': {
        'time_limit': 600,
        'soft_time_limit': 540,
        'priority': 3,
    },
    
    # ==================== 镜像管理任务 ====================
    'easytask.tasks.pull_docker_image': {
        'rate_limit': '50/m',
        'time_limit': 600,  # 10分钟
        'soft_time_limit': 540,
        'priority': 4,
    },
    'easytask.tasks.pull_multiple_docker_images': {
        'rate_limit': '10/m',
        'time_limit': 1800,  # 30分钟
        'soft_time_limit': 1740,
        'priority': 4,
    },
    'easytask.tasks.batch_check_images_status': {
        'time_limit': 300,
        'soft_time_limit': 270,
        'priority': 3,
        'expires': 1800,  # 30分钟过期（每小时执行）
    },
    
    # ==================== 排名更新任务 ====================
    'competition.tasks.update_competition_rankings': {
        'rate_limit': '30/m',
        'time_limit': 120,
        'soft_time_limit': 100,
        'priority': 5,
    },
    'competition.tasks.cleanup_failed_and_pending_pods': {
        'rate_limit': '60/m',  # 每分钟最多60次
        'time_limit': 180,
        'soft_time_limit': 150,
        'priority': 4,
    },
    
    # ==================== 维护任务 ====================
    'competition.tasks.cleanup_pending_tasks': {
        'time_limit': 180,
        'soft_time_limit': 150,
        'priority': 3,
    },
    'practice.tasks.cleanup_pending_tasks': {
        'time_limit': 180,
        'soft_time_limit': 150,
        'priority': 3,
    },
    'easytask.tasks.clear_all_caches': {
        'time_limit': 300,
        'soft_time_limit': 270,
        'priority': 2,
    },
    'easytask.tasks.sync_wiki_knowledge_base': {
        'time_limit': 600,
        'soft_time_limit': 540,
        'priority': 2,
    },
    'easytask.tasks.sync_external_knowledge_sources': {
        'time_limit': 1800,  # 30分钟
        'soft_time_limit': 1740,
        'priority': 2,
    },
    'easytask.tasks.sync_ctf_writeups': {
        'time_limit': 600,
        'soft_time_limit': 540,
        'priority': 2,
    },
    'easytask.tasks.cleanup_k8s_stale_pods': {
        'time_limit': 300,
        'soft_time_limit': 270,
        'priority': 4,
        'expires': 150,  # 2.5分钟过期（每5分钟执行）
    },
    'easytask.tasks.optimize_k8s_resources': {
        'time_limit': 300,
        'soft_time_limit': 270,
        'priority': 3,
        'expires': 300,  # 5分钟过期（每10分钟执行）
    },
    'easytask.tasks.check_docker_engines_health': {
        'time_limit': 120,
        'soft_time_limit': 100,
        'priority': 5,
    },
    'easytask.tasks.set_views_to_redis': {
        'time_limit': 300,
        'soft_time_limit': 270,
        'priority': 3,
    },
    'easytask.tasks.send_unread_notifications_email': {
        'time_limit': 300,
        'soft_time_limit': 270,
        'priority': 4,
    },
}

# Celery Beat 定期任务配置（使用 DatabaseScheduler，可在 Django Admin 中管理）
# 默认任务：定期清理过期容器
# 注意：旧版 CELERYBEAT_SCHEDULE 已废弃，任务已迁移到下方的 CELERY_BEAT_SCHEDULE
# *************************************** celery 配置结束 ***************************************


# ****************************************** 邮箱配置开始 ****************************************
# 配置管理邮箱，服务出现故障会收到到邮件，环境变量值的格式：name|test@test.com 多组用户用英文逗号隔开
ADMINS = []
admin_email_user = os.getenv('SNOW_ADMIN_EMAIL_USER')
if admin_email_user:
    for each in admin_email_user.split(','):
        a_user, a_email = each.split('|')
        ADMINS.append((a_user, a_email))

# 邮箱配置
# 使用自定义邮件后端，支持动态从数据库读取配置
# 优先使用数据库配置，如果数据库未配置则回退到以下环境变量配置
EMAIL_BACKEND = 'public.email_backend.DynamicEmailBackend'

# 环境变量配置作为后备（当数据库未配置时使用）
EMAIL_HOST = os.getenv('SNOW_EMAIL_HOST', 'smtp.163.com')
EMAIL_HOST_USER = os.getenv('SNOW_EMAIL_HOST_USER', '')
EMAIL_HOST_PASSWORD = os.getenv('SNOW_EMAIL_HOST_PASSWORD', '')  # 授权码
EMAIL_PORT = os.getenv('SNOW_EMAIL_PORT', 465)
EMAIL_TIMEOUT = 5
EMAIL_USE_SSL = os.getenv('SNOW_EMAIL_USE_SSL', 'True').upper() == 'TRUE'
# 确保 DEFAULT_FROM_EMAIL 有有效值，避免空字符串导致邮件发送失败
DEFAULT_FROM_EMAIL = os.getenv('SNOW_DEFAULT_FROM_EMAIL', EMAIL_HOST_USER if EMAIL_HOST_USER else 'noreply@example.com')
# *************************************** 邮箱配置结束 *******************************************


# ***************************************** 网站配置开始 ****************************************
# 网站默认设置和上下文信息


PROTOCOL_HTTPS = os.getenv('SNOW_PROTOCOL_HTTPS', 'HTTP').lower()
SECSNOW_VERSION  = os.getenv('SECSNOW_VERSION', 'v1.0.1')


#使用分析功能
SIMPLEUI_ANALYSIS = False

SIMPLEUI_HOME_INFO = False
# 自定义后台logo
SNOW_HOME_TITLE = os.getenv('SNOW_SIMPLEUI_HOME_TITLE', "SECSNOW")
SNOW_SIMPLEUI_LOGO = os.getenv('SNOW_SIMPLEUI_LOGO','https://www.secsnow.cn/static/blog/img/logo.svg')
SIMPLEUI_LOGO = f'{SNOW_SIMPLEUI_LOGO}'

# 自定义菜单图标
SIMPLEUI_ICON = {
    'K8s编排': 'fas fa-layer-group',
    'Group results': 'fas fa-tasks',  # Celery 任务结果
    '任务组结果': 'fas fa-object-group',  # Celery 任务组结果
}
# ***************************************** 网站配置结束 *****************************************
# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/




# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

# STATIC_URL = 'static/'  # 已在上面第258行定义，此处注释掉避免重复

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'



# 确保日志目录存在
LOGS_DIR = os.path.join(BASE_DIR, 'log')
if not os.path.exists(LOGS_DIR):
    os.makedirs(LOGS_DIR)

# 日志级别环境变量配置
# 使用方式: export LOG_LEVEL=INFO 或 export LOG_LEVEL_CONTAINER=DEBUG
# 优先级: 应用特定环境变量 > 全局环境变量 > 默认值
DEFAULT_LOG_LEVEL = os.getenv('LOG_LEVEL', 'INFO')

# 各应用的日志级别（支持独立配置）
LOG_LEVEL_DJANGO = os.getenv('LOG_LEVEL_DJANGO', DEFAULT_LOG_LEVEL)
LOG_LEVEL_APPS = os.getenv('LOG_LEVEL_APPS', DEFAULT_LOG_LEVEL)
LOG_LEVEL_COMPETITION = os.getenv('LOG_LEVEL_COMPETITION', DEFAULT_LOG_LEVEL)
LOG_LEVEL_QUIZ = os.getenv('LOG_LEVEL_QUIZ', DEFAULT_LOG_LEVEL)
LOG_LEVEL_CONTAINER = os.getenv('LOG_LEVEL_CONTAINER', 'WARNING')  # 容器应用默认 INFO
LOG_LEVEL_PRACTICE = os.getenv('LOG_LEVEL_PRACTICE', DEFAULT_LOG_LEVEL)
LOG_LEVEL_RECRUIT = os.getenv('LOG_LEVEL_RECRUIT', DEFAULT_LOG_LEVEL)
LOG_LEVEL_TOOL = os.getenv('LOG_LEVEL_TOOL', DEFAULT_LOG_LEVEL)
LOG_LEVEL_PUBLIC = os.getenv('LOG_LEVEL_PUBLIC', DEFAULT_LOG_LEVEL)
LOG_LEVEL_OAUTH = os.getenv('LOG_LEVEL_OAUTH', 'INFO')  # 认证应用默认 INFO
LOG_LEVEL_EASYTASK = os.getenv('LOG_LEVEL_EASYTASK', DEFAULT_LOG_LEVEL)
LOG_LEVEL_SNOWAI = os.getenv('LOG_LEVEL_SNOWAI', DEFAULT_LOG_LEVEL)

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {process:d} {thread:d} {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname} {message}',
            'style': '{',
        },
        'standard': {
            'format': '[{asctime}] {levelname} {name}: {message}',
            'style': '{',
            'datefmt': '%Y-%m-%d %H:%M:%S',
        },
    },
    'filters': {
        'require_debug_true': {
            '()': 'django.utils.log.RequireDebugTrue',
        },
        'require_debug_false': {
            '()': 'django.utils.log.RequireDebugFalse',
        },
    },
    'handlers': {
        'console': {
            'level': 'INFO',
            'filters': ['require_debug_true'],
            'class': 'logging.StreamHandler',
            'formatter': 'simple'
        },
        'file': {
            'level': 'INFO',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': os.path.join(LOGS_DIR, 'django.log'),
            'maxBytes': 10 * 1024 * 1024,  # 10 MB
            'backupCount': 5,
            'formatter': 'standard',
        },
        'database': {
            'level': 'WARNING',  # 只记录警告和错误到数据库
            'class': 'apps.logs.log_handlers.DatabaseLogHandler',
            'formatter': 'standard',
        },
        'mail_admins': {
            'level': 'ERROR',
            'filters': ['require_debug_false'],
            'class': 'django.utils.log.AdminEmailHandler',
            'formatter': 'verbose',
        },
    },
    'loggers': {
        'django': {
            'handlers': ['console', 'file'],
            'level': LOG_LEVEL_DJANGO,
            'propagate': True,
        },
        'django.request': {
            'handlers': ['mail_admins', 'file'],
            'level': 'ERROR',  # 请求错误始终记录
            'propagate': False,
        },
        'apps': {  # 通用应用日志
            'handlers': ['console', 'file'],
            'level': LOG_LEVEL_APPS,
            'propagate': False,
        },
        'apps.competition': {  # 比赛应用（重要）
            'handlers': ['console', 'file', 'database'],
            'level': LOG_LEVEL_COMPETITION,
            'propagate': False,
        },
        'apps.quiz': {  # 竞赛应用
            'handlers': ['console', 'file'],
            'level': LOG_LEVEL_QUIZ,
            'propagate': False,
        },
        'apps.container': {  # 容器应用（重要）
            'handlers': ['console', 'file', 'database'],
            'level': LOG_LEVEL_CONTAINER,
            'propagate': False,
        },
        'apps.practice': {  # 练习应用
            'handlers': ['console', 'file'],
            'level': LOG_LEVEL_PRACTICE,
            'propagate': False,
        },
        'apps.recruit': {  # 招聘应用
            'handlers': ['console', 'file'],
            'level': LOG_LEVEL_RECRUIT,
            'propagate': False,
        },
        'apps.tool': {  # 工具应用
            'handlers': ['console', 'file'],
            'level': LOG_LEVEL_TOOL,
            'propagate': False,
        },
        'apps.public': {  # 公共应用
            'handlers': ['console', 'file'],
            'level': LOG_LEVEL_PUBLIC,
            'propagate': False,
        },
        'apps.oauth': {  # 认证应用（重要）
            'handlers': ['console', 'file', 'database'],
            'level': LOG_LEVEL_OAUTH,
            'propagate': False,
        },
        'apps.easytask': {  # 任务应用
            'handlers': ['console', 'file', 'database'],
            'level': LOG_LEVEL_EASYTASK,
            'propagate': False,
        },
        'apps.snowai': {  # AI 应用
            'handlers': ['console', 'file', 'database'],
            'level': LOG_LEVEL_SNOWAI,
            'propagate': False,
        },
    }
}


SCHEDULED_TASK_SWITCHES_ENABLED = True






