# Generated by Django 5.1.6 on 2026-03-08 18:21

import django.core.validators
import django.db.models.deletion
import quiz.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_type', models.CharField(choices=[('single', '单项选择题'), ('multiple', '多项选择题'), ('judge', '判断题'), ('fill_blank', '填空题'), ('essay', '简答题')], db_index=True, max_length=20, verbose_name='题目类型')),
                ('content', models.TextField(help_text='支持Markdown格式', verbose_name='题目内容')),
                ('standard_answer', models.TextField(blank=True, help_text='填空题和简答题的标准答案', null=True, verbose_name='标准答案')),
                ('explanation', models.TextField(blank=True, null=True, verbose_name='答案解析')),
                ('score', models.DecimalField(decimal_places=2, default=1.0, max_digits=5, verbose_name='分数')),
                ('difficulty', models.CharField(choices=[('easy', '简单'), ('medium', '中等'), ('hard', '困难')], default='medium', max_length=20, verbose_name='难度')),
                ('category', models.CharField(blank=True, db_index=True, max_length=100, null=True, verbose_name='题目分类')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '题目',
                'verbose_name_plural': '题目',
                'db_table': 'quiz_question',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('F', 'F'), ('G', 'G'), ('H', 'H'), ('I', 'I'), ('J', 'J')], max_length=1, verbose_name='选项序号')),
                ('content', models.TextField(verbose_name='选项内容')),
                ('is_correct', models.BooleanField(default=False, verbose_name='是否正确答案')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='quiz.question', verbose_name='所属题目')),
            ],
            options={
                'verbose_name': '选项',
                'verbose_name_plural': '选项',
                'db_table': 'quiz_option',
                'ordering': ['order'],
                'unique_together': {('question', 'order')},
            },
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='竞赛标题')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='URL标识')),
                ('description', models.TextField(blank=True, null=True, verbose_name='竞赛说明')),
                ('cover_image', models.ImageField(blank=True, help_text='推荐尺寸：400x225像素（16:9比例），支持格式：JPG、PNG、WEBP、SVG，大小不超过5MB', null=True, upload_to=quiz.models.quiz_cover_image_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp', 'svg']), quiz.models.validate_quiz_cover_size], verbose_name='竞赛封面图片')),
                ('total_score', models.DecimalField(decimal_places=2, default=0.0, max_digits=7, verbose_name='总分')),
                ('pass_score', models.DecimalField(blank=True, decimal_places=2, default=0.0, help_text='留空或0时自动设置为总分的60%', max_digits=7, null=True, verbose_name='及格分数')),
                ('duration', models.IntegerField(default=60, verbose_name='考试时长(分钟)')),
                ('start_time', models.DateTimeField(blank=True, null=True, verbose_name='开始时间')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='结束时间')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('show_answer', models.BooleanField(default=True, verbose_name='显示答案解析')),
                ('max_attempts', models.IntegerField(default=1, help_text='0表示不限制次数', verbose_name='最大答题次数')),
                ('enable_pass_score', models.BooleanField(default=False, verbose_name='启用及格线')),
                ('show_leaderboard', models.BooleanField(default=True, verbose_name='显示排行榜')),
                ('max_violations', models.IntegerField(default=5, help_text='达到此次数将强制提交试卷', verbose_name='最大违规次数')),
                ('enable_anti_cheat', models.BooleanField(default=True, verbose_name='启用防作弊')),
                ('random_order', models.BooleanField(default=False, help_text='开启后，每个用户看到的题目顺序不同（同一用户多次查看顺序保持一致）', verbose_name='题目顺序随机')),
                ('require_registration', models.BooleanField(default=False, help_text='开启后，用户需要先报名才能参加竞赛', verbose_name='需要报名')),
                ('require_approval', models.BooleanField(default=False, help_text='开启后，报名需要管理员审核通过才能参加竞赛', verbose_name='报名需要审核')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('creator', models.ForeignKey(blank=True, help_text='留空表示系统管理员创建', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_quizzes', to=settings.AUTH_USER_MODEL, verbose_name='创建者')),
            ],
            options={
                'verbose_name': '知识竞赛',
                'verbose_name_plural': '知识竞赛',
                'db_table': 'quiz_quiz',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QuizQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=0, verbose_name='题目顺序')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_questions', to='quiz.question', verbose_name='题目')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_questions', to='quiz.quiz', verbose_name='所属竞赛')),
            ],
            options={
                'verbose_name': '竞赛题目',
                'verbose_name_plural': '竞赛题目',
                'db_table': 'quiz_quiz_question',
                'ordering': ['order'],
                'unique_together': {('quiz', 'question')},
            },
        ),
        migrations.AddField(
            model_name='quiz',
            name='questions',
            field=models.ManyToManyField(through='quiz.QuizQuestion', to='quiz.question', verbose_name='包含题目'),
        ),
        migrations.CreateModel(
            name='QuizRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='唯一标识')),
                ('status', models.CharField(choices=[('in_progress', '答题中'), ('completed', '已完成'), ('timeout', '超时'), ('cheating', '作弊被强制提交')], db_index=True, default='in_progress', max_length=20, verbose_name='状态')),
                ('score', models.DecimalField(db_index=True, decimal_places=2, default=0.0, max_digits=7, verbose_name='得分')),
                ('start_time', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='开始时间')),
                ('submit_time', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='提交时间')),
                ('violation_count', models.IntegerField(default=0, verbose_name='违规次数')),
                ('violation_logs', models.JSONField(blank=True, default=list, verbose_name='违规日志')),
                ('user_agent', models.TextField(blank=True, verbose_name='用户代理')),
                ('device_type', models.CharField(blank=True, max_length=20, verbose_name='设备类型')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='quiz.quiz', verbose_name='所属竞赛')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_records', to=settings.AUTH_USER_MODEL, verbose_name='答题用户')),
            ],
            options={
                'verbose_name': '答题记录',
                'verbose_name_plural': '答题记录',
                'db_table': 'quiz_record',
                'ordering': ['-start_time'],
            },
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_answer', models.TextField(blank=True, help_text='填空题和简答题的答案', null=True, verbose_name='文本答案')),
                ('is_correct', models.BooleanField(default=False, verbose_name='是否正确')),
                ('manual_score', models.DecimalField(blank=True, decimal_places=2, help_text='简答题的人工评分，为空表示未批改', max_digits=5, null=True, verbose_name='人工评分')),
                ('review_comment', models.TextField(blank=True, null=True, verbose_name='批改评语')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='批改时间')),
                ('locked_at', models.DateTimeField(blank=True, null=True, verbose_name='锁定时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='答题时间')),
                ('locked_by', models.ForeignKey(blank=True, help_text='正在批改此答案的阅卷人', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='locked_answers', to=settings.AUTH_USER_MODEL, verbose_name='锁定人')),
                ('reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_answers', to=settings.AUTH_USER_MODEL, verbose_name='批改人')),
                ('selected_options', models.ManyToManyField(blank=True, to='quiz.option', verbose_name='选择的选项')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.question', verbose_name='题目')),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='quiz.quizrecord', verbose_name='答题记录')),
            ],
            options={
                'verbose_name': '答题日志',
                'verbose_name_plural': '答题日志',
                'db_table': 'quiz_answer',
            },
        ),
        migrations.CreateModel(
            name='QuizRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', '待审核'), ('approved', '已通过'), ('rejected', '已拒绝')], db_index=True, default='approved', max_length=20, verbose_name='审核状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='报名时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='quiz.quiz', verbose_name='所属竞赛')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户ID')),
            ],
            options={
                'verbose_name': '竞赛报名',
                'verbose_name_plural': '竞赛报名',
                'db_table': 'quiz_registration',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QuizGrader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='added_graders', to=settings.AUTH_USER_MODEL, verbose_name='添加人')),
                ('grader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='阅卷人')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='graders', to='quiz.quiz', verbose_name='所属竞赛')),
            ],
            options={
                'verbose_name': '阅卷人',
                'verbose_name_plural': '阅卷人',
                'db_table': 'quiz_grader',
                'ordering': ['-created_at'],
                'unique_together': {('quiz', 'grader')},
            },
        ),
        migrations.AddIndex(
            model_name='quizrecord',
            index=models.Index(fields=['quiz', 'user', 'status'], name='quiz_record_quiz_id_ae547d_idx'),
        ),
        migrations.AddIndex(
            model_name='quizrecord',
            index=models.Index(fields=['quiz', 'status', '-score'], name='quiz_record_quiz_id_ba4978_idx'),
        ),
        migrations.AddIndex(
            model_name='quizrecord',
            index=models.Index(fields=['user', '-start_time'], name='quiz_record_user_id_3d23d5_idx'),
        ),
        migrations.AddIndex(
            model_name='quizrecord',
            index=models.Index(fields=['uuid', 'user'], name='quiz_record_uuid_310abc_idx'),
        ),
        migrations.AddIndex(
            model_name='quizrecord',
            index=models.Index(fields=['status', 'submit_time'], name='quiz_record_status_1b36e5_idx'),
        ),
        migrations.AddConstraint(
            model_name='quizrecord',
            constraint=models.CheckConstraint(condition=models.Q(('score__gte', 0)), name='quiz_record_score_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='quizrecord',
            constraint=models.CheckConstraint(condition=models.Q(('violation_count__gte', 0)), name='quiz_record_violation_non_negative'),
        ),
        migrations.AlterUniqueTogether(
            name='answer',
            unique_together={('record', 'question')},
        ),
        migrations.AddIndex(
            model_name='quizregistration',
            index=models.Index(fields=['quiz', 'status'], name='quiz_regist_quiz_id_1a1976_idx'),
        ),
        migrations.AddIndex(
            model_name='quizregistration',
            index=models.Index(fields=['user', '-created_at'], name='quiz_regist_user_id_3eace3_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='quizregistration',
            unique_together={('quiz', 'user')},
        ),
    ]
