# Generated by Django 5.1.6 on 2026-03-08 18:21

import django.core.validators
import recruit.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True, verbose_name='城市名称')),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('description', models.TextField(default='暂无描述', help_text='用来作为SEO中description,长度参考SEO标准', verbose_name='描述')),
            ],
            options={
                'verbose_name': '城市配置',
                'verbose_name_plural': '城市配置',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100, verbose_name='公司名称')),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('description', models.TextField(default='暂无描述', help_text='用来作为SEO中description,长度参考SEO标准', verbose_name='描述')),
                ('company_size', models.CharField(blank=True, choices=[('<15', '15人以下'), ('15-50', '15-50人'), ('50-150', '50-150人'), ('150-500', '150-500人'), ('500-2000', '500-2000人'), ('>2000', '2000人以上')], max_length=20, verbose_name='公司规模')),
                ('company_homepage', models.URLField(blank=True, verbose_name='公司官网')),
                ('contact_email', models.EmailField(blank=True, max_length=254, verbose_name='HR 邮箱')),
                ('website', models.URLField(blank=True, help_text='招聘官网', verbose_name='招聘官网')),
            ],
            options={
                'verbose_name': '公司配置',
                'verbose_name_plural': '公司配置',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True, verbose_name='岗位关键字')),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('description', models.TextField(default='暂无描述', help_text='用来作为SEO中description,长度参考SEO标准', verbose_name='描述')),
            ],
            options={
                'verbose_name': '标签配置',
                'verbose_name_plural': '标签配置',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='职位名称')),
                ('track', models.CharField(choices=[('redteam', '红队'), ('blueteam', '蓝队'), ('secdev', '安全开发'), ('reversing', '逆向/恶意分析'), ('iot', '物联网安全'), ('cloud', '云安全'), ('compliance', '合规/等保'), ('carrisk', '车联网安全'), ('audit', '安全审计'), ('onsite', '驻场服务'), ('operations', '安全运营'), ('Penetration', '渗透测试'), ('safetest', '安全测试'), ('analysis', '安全分析'), ('other', '其它')], default='other', max_length=20, verbose_name='安全方向')),
                ('RecruitmentType', models.CharField(choices=[('school', '校招'), ('society', '社招'), ('internship', '实习')], default='school', max_length=20, verbose_name='招聘类型')),
                ('description', models.TextField(help_text='支持 Markdown', verbose_name='职位描述')),
                ('requirements', models.TextField(help_text='支持 Markdown', verbose_name='任职要求')),
                ('apply_link', models.URLField(blank=True, help_text='可填 Boss/拉勾/官网链接', verbose_name='在线投递链接')),
                ('Internal_push', models.CharField(blank=True, max_length=30, verbose_name='内推码')),
                ('salary_min', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='最低年薪(k)')),
                ('salary_max', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='最高年薪(k)')),
                ('address', models.CharField(blank=True, max_length=200, verbose_name='来源')),
                ('is_published', models.BooleanField(default=True, verbose_name='立即发布')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('expire_at', models.DateTimeField(default=recruit.models._default_expire, verbose_name='过期时间')),
                ('slug', models.SlugField(help_text='留空将自动生成', max_length=140, unique=True, verbose_name='URL')),
                ('views', models.IntegerField(default=0, verbose_name='阅览量')),
                ('cityname', models.ManyToManyField(blank=True, to='recruit.city', verbose_name='城市')),
                ('companyname', models.ManyToManyField(blank=True, to='recruit.company', verbose_name='公司')),
                ('send_author', models.ManyToManyField(blank=True, related_name='send_authors', to=settings.AUTH_USER_MODEL, verbose_name='投递人员')),
                ('page_keywords', models.ManyToManyField(blank=True, to='recruit.tag', verbose_name='标签')),
            ],
            options={
                'verbose_name': '岗位配置',
                'verbose_name_plural': '岗位配置',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='recruit_job_created_921ac5_idx'), models.Index(fields=['track', '-created_at'], name='recruit_job_track_e944b1_idx')],
            },
        ),
    ]
