# Generated by Django 5.1.6 on 2026-03-08 18:21

import imagekit.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutBlog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(verbose_name='About 内容')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
            ],
            options={
                'verbose_name': 'About',
                'verbose_name_plural': 'About',
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='文章标题')),
                ('summary', models.TextField(default='文章摘要等同于网页description内容，请务必填写...', max_length=230, verbose_name='文章摘要')),
                ('body', models.TextField(verbose_name='文章内容')),
                ('img_link', imagekit.models.fields.ProcessedImageField(blank=True, help_text='上传图片大小建议使用5:5的宽高比，为了清晰度原始图片宽度应该超过480px', null=True, upload_to='article/upload/%Y/%m/%d/', verbose_name='封面图')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('views', models.IntegerField(default=0, verbose_name='阅览量')),
                ('slug', models.SlugField(unique=True)),
                ('is_top', models.BooleanField(default=False, verbose_name='置顶')),
                ('is_publish', models.BooleanField(default=True, verbose_name='是否发布')),
                ('is_memberShow', models.BooleanField(default=False, verbose_name='是否是会员文章')),
                ('topic_order', models.IntegerField(blank=True, default=99, help_text='仅作为文章在主题中的排序', null=True, verbose_name='主题中排序')),
                ('topic_short_title', models.CharField(blank=True, help_text='专门给Topic使用的短标题', max_length=50, null=True, verbose_name='主题短标题')),
            ],
            options={
                'verbose_name': '文章',
                'verbose_name_plural': '文章',
                'ordering': ['-create_date'],
            },
        ),
        migrations.CreateModel(
            name='ArticleView',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=10, unique=True, verbose_name='统计日期')),
                ('body', models.TextField(verbose_name='统计数据')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='录入时间')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '文章浏览量统计',
                'verbose_name_plural': '文章浏览量统计',
                'ordering': ['create_date'],
            },
        ),
        migrations.CreateModel(
            name='Carousel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(help_text='编号决定图片播放的顺序，图片不要多于5张', verbose_name='编号')),
                ('title', models.CharField(blank=True, help_text='标题可以为空', max_length=20, null=True, verbose_name='标题')),
                ('content', models.CharField(max_length=80, verbose_name='描述')),
                ('img_url', models.CharField(max_length=200, verbose_name='图片地址')),
                ('url', models.CharField(default='#', help_text='图片跳转的超链接，默认#表示不跳转', max_length=200, verbose_name='跳转链接')),
            ],
            options={
                'verbose_name': '图片轮播',
                'verbose_name_plural': '图片轮播',
                'ordering': ['number', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='文章分类')),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(default='分类描述', help_text='用来作为SEO中description,长度参考SEO标准', max_length=240, verbose_name='描述')),
            ],
            options={
                'verbose_name': '分类',
                'verbose_name_plural': '分类',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='FeedHub',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='名称')),
                ('url', models.CharField(max_length=255, verbose_name='feed地址')),
                ('icon', models.TextField(help_text='可以填写base64图片格式或者图标地址', verbose_name='图标地址')),
                ('is_active', models.BooleanField(default=True, help_text='作为是否采集的标识', verbose_name='是否有效')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='录入时间')),
                ('data', models.TextField(blank=True, help_text='定义任务采集数据', null=True, verbose_name='数据')),
                ('sort_order', models.IntegerField(default=99, help_text='作为显示的时候的顺序', verbose_name='排序')),
            ],
            options={
                'verbose_name': 'Feed Hub',
                'verbose_name_plural': 'Feed Hub',
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='FriendLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='网站名称')),
                ('description', models.CharField(blank=True, max_length=100, verbose_name='网站描述')),
                ('link', models.URLField(help_text='请填写http或https开头的完整形式地址', verbose_name='友链地址')),
                ('logo', imagekit.models.fields.ProcessedImageField(blank=True, default='friend/default/default.png', help_text='上传图片大小建议120x120以上，使用友联域名命名，如tendcode.com.png', upload_to='friend/upload/%Y', verbose_name='网站LOGO')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否有效')),
                ('is_show', models.BooleanField(default=False, verbose_name='是否展示')),
                ('not_show_reason', models.CharField(blank=True, max_length=50, null=True, verbose_name='禁用原因')),
            ],
            options={
                'verbose_name': '友情链接',
                'verbose_name_plural': '友情链接',
                'ordering': ['create_date'],
            },
        ),
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='文章关键词')),
            ],
            options={
                'verbose_name': '关键词',
                'verbose_name_plural': '关键词',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PageView',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=255, unique=True, verbose_name='页面地址')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='页面名称')),
                ('views', models.IntegerField(default=0, verbose_name='浏览量')),
                ('is_compute', models.BooleanField(default=True, verbose_name='是否计算到访问量')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='录入时间')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '单页面浏览量',
                'verbose_name_plural': '单页面浏览量',
                'ordering': ['url'],
            },
        ),
        migrations.CreateModel(
            name='PrivacyBlog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(verbose_name='用户服务协议与隐私保护内容')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
            ],
            options={
                'verbose_name': '协议与隐私',
                'verbose_name_plural': '协议与隐私',
            },
        ),
        migrations.CreateModel(
            name='Silian',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('badurl', models.CharField(help_text='注意：地址是以http开头的完整链接格式', max_length=200, verbose_name='死链地址')),
                ('remark', models.CharField(blank=True, max_length=50, null=True, verbose_name='死链说明')),
                ('add_date', models.DateTimeField(auto_now_add=True, verbose_name='提交日期')),
            ],
            options={
                'verbose_name': '死链',
                'verbose_name_plural': '死链',
                'ordering': ['-add_date'],
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='专题名称')),
                ('status', models.CharField(choices=[('not_started', '未开始'), ('ongoing', '连载中'), ('completed', '已完结')], default='not_started', max_length=20, verbose_name='状态')),
                ('description', models.CharField(max_length=250, verbose_name='描述')),
                ('sort_order', models.IntegerField(default=99, help_text='作为专题列表页的排序', verbose_name='排序')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('cover_image', imagekit.models.fields.ProcessedImageField(default='subject/default/default.png', help_text='上传图片大小建议使用5:3的宽高比，为了清晰度原始图片宽度应该超过250px', upload_to='subject/upload/%Y/%m/%d/', verbose_name='封面图')),
            ],
            options={
                'verbose_name': '专题',
                'verbose_name_plural': '专题',
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='文章标签')),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(default='标签描述', help_text='用来作为SEO中description,长度参考SEO标准', max_length=240, verbose_name='描述')),
            ],
            options={
                'verbose_name': '标签',
                'verbose_name_plural': '标签',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Timeline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('side', models.CharField(choices=[('L', '左边'), ('R', '右边')], default='L', max_length=1, verbose_name='位置')),
                ('star_num', models.IntegerField(choices=[(1, '1颗星'), (2, '2颗星'), (3, '3颗星'), (4, '4颗星'), (5, '5颗星')], default=3, verbose_name='星星个数')),
                ('icon', models.CharField(default='fa fa-pencil', max_length=50, verbose_name='图标')),
                ('icon_color', models.CharField(choices=[('primary', '基本-蓝色'), ('success', '成功-绿色'), ('info', '信息-天蓝色'), ('warning', '警告-橙色'), ('danger', '危险-红色')], default='info', max_length=20, verbose_name='图标颜色')),
                ('title', models.CharField(max_length=100, verbose_name='标题')),
                ('update_date', models.DateTimeField(verbose_name='更新时间')),
                ('content', models.TextField(verbose_name='主要内容')),
            ],
            options={
                'verbose_name': '时间线',
                'verbose_name_plural': '时间线',
                'ordering': ['-update_date'],
            },
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='主题名称')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('sort_order', models.IntegerField(default=99, help_text='仅作为主题在专题中的排序，类似目录', verbose_name='排序')),
            ],
            options={
                'verbose_name': '专题-主题',
                'verbose_name_plural': '专题-主题',
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='vulnerabilitywiki',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
