# Generated by Django 5.1.6 on 2026-03-08 18:21

import django.contrib.sites.models
import django.core.validators
import django.db.models.deletion
import public.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('practice', '0001_initial'),
        ('recruit', '0001_initial'),
        ('sites', '0002_alter_domain_unique'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FooterColumn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='栏目标题')),
                ('order', models.IntegerField(default=0, help_text='数字越小越靠前', verbose_name='排序')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否显示')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '页脚栏目',
                'verbose_name_plural': '页脚栏目',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='HomePageConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_title', models.CharField(default='小雪花安全实验室', max_length=100, verbose_name='主标题')),
                ('main_subtitle', models.CharField(default='SECSNOW', max_length=100, verbose_name='副标题')),
                ('main_description', models.TextField(default='一个致力于开源、共享、共创的网络安全、数据安全、人工智能安全研究的实验室， 我们的使命：坚决保护国家网络安全。', verbose_name='主描述')),
                ('main_image', models.FileField(blank=True, help_text='支持格式：JPG、PNG、GIF、WEBP、SVG，建议尺寸：800x600', null=True, upload_to=public.models.homepage_main_image_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif', 'webp', 'svg'])], verbose_name='主图片')),
                ('service_badge', models.CharField(default='Get started', max_length=50, verbose_name='服务标签')),
                ('service_title', models.CharField(default='我们的服务与价值', max_length=100, verbose_name='服务标题')),
                ('service_description', models.TextField(default='伟大的服务源于对他人需求的深刻理解。', verbose_name='服务描述')),
                ('is_active', models.BooleanField(default=True, help_text='只能有一个启用的配置', verbose_name='是否启用')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '首页配置',
                'verbose_name_plural': '首页配置',
                'ordering': ['-is_active', '-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='MotivationalQuote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=200, verbose_name='语录内容')),
                ('author', models.CharField(blank=True, max_length=50, null=True, verbose_name='作者')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '励志语录',
                'verbose_name_plural': '励志语录',
                'ordering': ['?'],
            },
        ),
        migrations.CreateModel(
            name='RewardItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='奖品名称')),
                ('description', models.TextField(verbose_name='奖品描述')),
                ('coins', models.PositiveIntegerField(default=100, validators=[django.core.validators.MinValueValidator(1)], verbose_name='所需金币')),
                ('image', models.FileField(help_text='支持格式：JPG、PNG、WEBP、SVG，大小不超过2MB', upload_to=public.models.reward_image_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp', 'svg']), public.models.validate_image_size], verbose_name='奖品图片')),
                ('stock', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='剩余数量')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否可兑换')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '奖品',
                'verbose_name_plural': '奖品',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ServiceCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='卡片标题')),
                ('description', models.TextField(verbose_name='卡片描述')),
                ('image', models.FileField(blank=True, help_text='支持格式：JPG、PNG、GIF、WEBP、SVG，建议尺寸：400x300', null=True, upload_to=public.models.service_card_image_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif', 'webp', 'svg'])], verbose_name='卡片图片')),
                ('order', models.IntegerField(default=0, help_text='数字越小越靠前', verbose_name='排序')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否显示')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '服务卡片',
                'verbose_name_plural': '服务卡片',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='SECSNOW', max_length=100, verbose_name='网站名称')),
                ('site_logo', models.FileField(blank=True, help_text='网站Logo图片，支持格式：JPG、PNG、SVG等，留空使用默认 blog/img/logo.svg', null=True, upload_to=public.models.site_logo_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif', 'webp', 'svg'])], verbose_name='网站Logo')),
                ('site_favicon', models.FileField(blank=True, help_text='网站图标（显示在浏览器标签栏），支持格式：ICO、PNG、SVG等，留空使用默认 public/img/favicon.ico', null=True, upload_to=public.models.site_favicon_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['ico', 'png', 'jpg', 'jpeg', 'svg'])], verbose_name='网站Favicon')),
                ('site_description', models.CharField(default='SECSNOW 一个开源、共创、共享网络安全技术学习网站', max_length=200, verbose_name='网站描述')),
                ('site_keywords', models.CharField(default='secsnow,CTF竞赛、漏洞靶场、网络安全', max_length=200, verbose_name='网站关键词')),
                ('site_create_date', models.DateField(help_text='用于计算网站运行天数', verbose_name='网站创建日期')),
                ('beian', models.CharField(blank=True, default='', max_length=50, verbose_name='ICP备案号')),
                ('cnzz_code', models.TextField(blank=True, help_text='直接粘贴完整的统计代码', verbose_name='站长统计代码（友盟）')),
                ('la51_code', models.TextField(blank=True, help_text='直接粘贴完整的统计代码', verbose_name='站长统计代码（51.la）')),
                ('site_verification', models.TextField(blank=True, help_text='用于站长平台推送验证', verbose_name='站长验证代码')),
                ('email_enabled', models.BooleanField(default=False, help_text='是否启用邮箱功能。验证方式请在请在.env 中配置 SNOW_ACCOUNT_EMAIL_VERIFICATION （none/optional/mandatory）', verbose_name='启用邮箱功能')),
                ('email_host', models.CharField(blank=True, default='smtp.163.com', help_text='SMTP服务器地址，如: smtp.qq.com, smtp.163.com, smtp.gmail.com', max_length=100, verbose_name='SMTP服务器')),
                ('email_port', models.IntegerField(blank=True, default=465, help_text='SMTP端口号：SSL使用465，TLS使用587', verbose_name='SMTP端口')),
                ('email_host_user', models.EmailField(blank=True, help_text='用于SMTP认证的邮箱地址，只填写纯邮箱地址即可，如: admin@example.com', max_length=100, verbose_name='发件人邮箱')),
                ('email_host_password', models.CharField(blank=True, help_text='邮箱SMTP授权码（注意：不是邮箱登录密码，需要在邮箱设置中生成）', max_length=100, verbose_name='授权码')),
                ('email_use_ssl', models.BooleanField(default=True, help_text='勾选使用SSL（端口465），不勾选使用TLS（端口587）', verbose_name='使用SSL')),
                ('email_from', models.CharField(blank=True, default='SECSNOW', help_text='发件人显示名称（只填写名称，不要包含邮箱地址），如: SECSNOW、网站管理员等', max_length=100, verbose_name='发件人名称')),
                ('github_login_enabled', models.BooleanField(default=False, help_text='是否显示GitHub快速登录按钮', verbose_name='启用GitHub登录')),
                ('registration_enabled', models.BooleanField(default=True, help_text='关闭后，新用户将无法注册账号（管理员后台添加不受影响）', verbose_name='允许用户注册')),
                ('footer_style', models.CharField(choices=[('dark', '深色页脚（默认）'), ('light', '浅色页脚（白色）')], default='dark', help_text='选择页脚的颜色风格', max_length=10, verbose_name='页脚风格')),
                ('anime_side_left_image', models.FileField(blank=True, help_text='简洁版比赛页面主背景左侧装饰图片，建议尺寸：高度与页面等高，宽度200-400px，支持透明PNG', null=True, upload_to='site_images/anime/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif', 'webp'])], verbose_name='左侧装饰图片')),
                ('anime_side_right_image', models.FileField(blank=True, help_text='简洁版比赛页面主背景右侧装饰图片，建议尺寸：高度与页面等高，宽度200-400px，支持透明PNG', null=True, upload_to='site_images/anime/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif', 'webp'])], verbose_name='右侧装饰图片')),
                ('anime_filter_right_image', models.FileField(blank=True, help_text='题目筛选框右侧装饰图片，建议尺寸：300x300px，支持透明PNG', null=True, upload_to='site_images/anime/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif', 'webp'])], verbose_name='筛选框右侧图片')),
                ('anime_challenge_start_bg', models.FileField(blank=True, help_text='答题启动按钮区域背景图，建议尺寸：1200x600px或更大，支持透明PNG', null=True, upload_to='site_images/anime/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif', 'webp'])], verbose_name='答题启动背景图')),
                ('is_active', models.BooleanField(default=True, help_text='只能有一个启用的配置', verbose_name='是否启用')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '网站配置',
                'verbose_name_plural': '网站配置',
                'ordering': ['-is_active', '-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='PublicSite',
            fields=[
            ],
            options={
                'verbose_name': '站点',
                'verbose_name_plural': '站点管理',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('sites.site',),
            managers=[
                ('objects', django.contrib.sites.models.SiteManager()),
            ],
        ),
        migrations.CreateModel(
            name='CTFUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=0, verbose_name='用户分数')),
                ('coins', models.IntegerField(default=10, verbose_name='用户金币')),
                ('rank', models.IntegerField(default=0, verbose_name='用户排名')),
                ('solves', models.IntegerField(default=0, verbose_name='用户解题数')),
                ('collect_challenges', models.ManyToManyField(blank=True, default=None, related_name='collected_by_users', to='practice.pc_challenge', verbose_name='用户收藏的题目')),
                ('collect_jobs', models.ManyToManyField(blank=True, default=None, related_name='collected_by_users', to='recruit.job', verbose_name='用户收藏的岗位')),
                ('solved_challenges', models.ManyToManyField(blank=True, default=None, related_name='solved_by_users', to='practice.pc_challenge', verbose_name='已解决的题目')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '用户数据',
                'verbose_name_plural': '用户数据',
                'db_table': 'practice_ctfuser',
            },
        ),
        migrations.CreateModel(
            name='FooterLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='链接文本')),
                ('url', models.CharField(help_text='可以是URL或Django URL name', max_length=200, verbose_name='链接地址')),
                ('url_type', models.CharField(choices=[('url', '直接URL'), ('name', 'Django URL Name')], default='url', max_length=10, verbose_name='链接类型')),
                ('target', models.CharField(choices=[('_self', '当前窗口'), ('_blank', '新窗口')], default='_self', max_length=10, verbose_name='打开方式')),
                ('order', models.IntegerField(default=0, help_text='数字越小越靠前', verbose_name='排序')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否显示')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('column', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='public.footercolumn', verbose_name='所属栏目')),
            ],
            options={
                'verbose_name': '页脚链接',
                'verbose_name_plural': '页脚链接',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ExchangeRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact', models.CharField(max_length=50, verbose_name='联系方式')),
                ('is_processed', models.BooleanField(default=False, verbose_name='是否处理')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
                ('reward', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='public.rewarditem', verbose_name='奖品')),
            ],
            options={
                'verbose_name': '兑换记录',
                'verbose_name_plural': '兑换记录',
                'ordering': ['-created_at'],
            },
        ),
    ]
