# Generated by Django 5.1.6 on 2026-03-08 18:21

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('container', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SolveRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solved_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '解题记录',
                'verbose_name_plural': '解题记录',
                'ordering': ['-solved_at'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='学习岛标签')),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('description', models.TextField(default='暂无描述', help_text='学习岛标签描述，支持Markdown格式', verbose_name='描述')),
            ],
            options={
                'verbose_name': '学习岛',
                'verbose_name_plural': '学习岛',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='PC_Challenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='唯一标识符')),
                ('title', models.CharField(max_length=255, verbose_name='题目标题')),
                ('description', models.TextField(verbose_name='题目描述')),
                ('category', models.CharField(choices=[('签到', '签到'), ('Web', 'Web'), ('Pwn', 'Pwn'), ('逆向', '逆向工程'), ('密码学', '密码学'), ('杂项', '杂项'), ('综合渗透', '综合渗透'), ('数字取证', '数字取证'), ('内存取证', '内存取证'), ('磁盘取证', '磁盘取证'), ('流量分析', '流量分析'), ('日志分析', '日志分析'), ('移动安全', '移动安全'), ('Android', 'Android'), ('iOS', 'iOS'), ('物联网', '物联网'), ('区块链', '区块链'), ('智能合约', '智能合约'), ('云安全', '云安全'), ('容器安全', '容器安全'), ('AI安全', 'AI安全'), ('机器学习', '机器学习'), ('开源情报', '开源情报'), ('隐写术', '隐写术'), ('编程', '编程'), ('硬件安全', '硬件安全'), ('无线电', '无线电'), ('CVE复现', 'CVE复现'), ('渗透测试', '渗透测试'), ('红队', '红队'), ('蓝队', '蓝队'), ('AD域渗透', 'AD域渗透'), ('内网渗透', '内网渗透'), ('Web3', 'Web3'), ('元宇宙', '元宇宙'), ('游戏安全', '游戏安全'), ('车联网', '车联网'), ('其他', '其他')], default='WEB', max_length=20, verbose_name='题目类型')),
                ('difficulty', models.CharField(choices=[('Easy', '简单'), ('Medium', '中等'), ('Hard', '困难')], default='Medium', max_length=10, verbose_name='难度')),
                ('points', models.IntegerField(default=100, verbose_name='分数')),
                ('flag_type', models.CharField(choices=[('STATIC', '静态Flag'), ('DYNAMIC', '动态flag')], default='DYNAMIC', max_length=20, verbose_name='Flag类型')),
                ('flag_template', models.TextField(blank=True, help_text='静态Flag：多个答案用英文逗号分隔，如 flag{answer1},flag{answer2}；动态Flag：填写数量即可自动生成多个', null=True, verbose_name='Flag值')),
                ('flag_count', models.IntegerField(default=1, help_text='题目flag的数量（1-10个）。静态Flag会自动检测逗号分隔的数量，动态Flag需手动设置生成数量', verbose_name='Flag数量')),
                ('flag_points', models.JSONField(blank=True, default=list, help_text='为每个flag配置分数，如 [10, 20, 30, 40]。必须满足：①数组长度=flag数量 ②总和=题目总分 ③全为正整数。不符合规则时自动重置为平均分配', null=True, verbose_name='各Flag分数配置')),
                ('coins', models.IntegerField(default=4, verbose_name='金币')),
                ('solves', models.IntegerField(default=0, verbose_name='解决次数')),
                ('views', models.IntegerField(default=0, verbose_name='浏览量')),
                ('static_file_url', models.URLField(blank=True, help_text='填写静态文件的URL地址，如果填写了URL地址，则优先使用URL地址，否则使用静态文件', max_length=500, null=True, verbose_name='静态文件URL')),
                ('first_blood_time', models.DateTimeField(blank=True, null=True, verbose_name='首次解决时间')),
                ('reward_coins', models.IntegerField(default=0, verbose_name='奖励金币')),
                ('allocated_coins', models.IntegerField(default=0, verbose_name='已分配给作者的金币')),
                ('hint', models.TextField(blank=True, help_text='题目解析内容，支持 Markdown 格式', null=True, verbose_name='题目解析/WriteUp')),
                ('writeup_is_public', models.BooleanField(default=False, help_text='勾选后所有用户可免费查看题解', verbose_name='题解是否公开')),
                ('writeup_cost', models.IntegerField(default=1, help_text='用户查看题解需要消耗的金币数（公开时无需消耗）', verbose_name='题解金币成本')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否激活')),
                ('is_top', models.BooleanField(default=False, verbose_name='置顶')),
                ('is_disable', models.BooleanField(default=True, verbose_name='是否全局启用')),
                ('is_member', models.BooleanField(default=False, verbose_name='是为会员题目')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='作者')),
                ('docker_image', models.ForeignKey(blank=True, help_text='选择镜像配置', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='practice_challenges', to='container.dockerimage', verbose_name='镜像配置')),
                ('first_blood_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='practice_first_blood_challenges', to=settings.AUTH_USER_MODEL, verbose_name='首次解决用户')),
                ('network_topology_config', models.ForeignKey(blank=True, help_text='如果是多场景题目，关联到具体的场景配置', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='practice_challenges', to='container.networktopologyconfig', verbose_name='多场景题目')),
                ('static_files', models.ForeignKey(blank=True, help_text='选择要使用的静态文件（仅用于静态文件部署）', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='practice_tasks_static_files', to='container.staticfile', verbose_name='静态文件')),
                ('writeup_purchased_by', models.ManyToManyField(blank=True, related_name='purchased_writeups', to=settings.AUTH_USER_MODEL, verbose_name='已购买题解的用户')),
            ],
            options={
                'verbose_name': '题目配置',
                'verbose_name_plural': '题目配置',
            },
        ),
        migrations.CreateModel(
            name='SolvedFlag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flag_index', models.IntegerField(help_text='该flag在题目中的索引（0-based）', verbose_name='Flag索引')),
                ('points_earned', models.IntegerField(default=0, verbose_name='获得分数')),
                ('solved_at', models.DateTimeField(auto_now_add=True, verbose_name='解决时间')),
                ('flag_hash', models.CharField(blank=True, help_text='用于验证flag唯一性', max_length=64, verbose_name='Flag哈希')),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='practice.pc_challenge', verbose_name='题目')),
            ],
            options={
                'verbose_name': 'FLAG记录',
                'verbose_name_plural': 'FLAG记录',
                'ordering': ['-solved_at'],
            },
        ),
    ]
