# Generated by Django 5.1.6 on 2026-03-08 18:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('practice', '0001_initial'),
        ('public', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='solvedflag',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='public.ctfuser', verbose_name='用户'),
        ),
        migrations.AddField(
            model_name='solverecord',
            name='challenge',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='practice.pc_challenge'),
        ),
        migrations.AddField(
            model_name='solverecord',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='public.ctfuser'),
        ),
        migrations.AddField(
            model_name='pc_challenge',
            name='tags',
            field=models.ManyToManyField(blank=True, to='practice.tag', verbose_name='学习岛标签'),
        ),
        migrations.AddIndex(
            model_name='solvedflag',
            index=models.Index(fields=['user', 'challenge'], name='practice_so_user_id_c5c1f2_idx'),
        ),
        migrations.AddIndex(
            model_name='solvedflag',
            index=models.Index(fields=['challenge', 'solved_at'], name='practice_so_challen_245ea8_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='solvedflag',
            unique_together={('user', 'challenge', 'flag_index')},
        ),
    ]
