# Generated by Django 5.1.6 on 2026-03-08 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SystemLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='记录时间')),
                ('level', models.CharField(choices=[('DEBUG', 'DEBUG'), ('INFO', 'INFO'), ('WARNING', 'WARNING'), ('ERROR', 'ERROR'), ('CRITICAL', 'CRITICAL')], max_length=10, verbose_name='日志级别')),
                ('logger_name', models.CharField(max_length=100, verbose_name='日志器名称')),
                ('message', models.TextField(verbose_name='日志消息')),
                ('user', models.CharField(blank=True, max_length=100, null=True, verbose_name='用户')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP地址')),
                ('request_path', models.CharField(blank=True, max_length=255, null=True, verbose_name='请求路径')),
                ('module', models.CharField(blank=True, max_length=100, null=True, verbose_name='模块')),
                ('function', models.CharField(blank=True, max_length=100, null=True, verbose_name='函数')),
                ('stack_trace', models.TextField(blank=True, null=True, verbose_name='堆栈跟踪')),
            ],
            options={
                'verbose_name': '系统日志',
                'verbose_name_plural': '系统日志',
                'ordering': ['-timestamp'],
            },
        ),
    ]
