# Generated by Django 5.1.6 on 2025-02-26 16:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('challenge', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='challenge',
            name='first_blood_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='first_blood_challenges', to=settings.AUTH_USER_MODEL, verbose_name='首次解决用户'),
        ),
        migrations.AddField(
            model_name='dockercompose',
            name='author',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='创建者'),
        ),
        migrations.AddField(
            model_name='challenge',
            name='docker_compose',
            field=models.ForeignKey(blank=True, help_text='选择Docker Compose配置（仅用于Docker Compose部署）', null=True, on_delete=django.db.models.deletion.SET_NULL, to='challenge.dockercompose', verbose_name='Docker Compose配置'),
        ),
        migrations.AddField(
            model_name='dockerimages',
            name='author',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='创建者'),
        ),
        migrations.AddField(
            model_name='challenge',
            name='docker_images',
            field=models.ManyToManyField(blank=True, help_text='选择要使用的Docker镜像（仅用于Docker镜像部署）', to='challenge.dockerimages', verbose_name='Docker镜像'),
        ),
        migrations.AddField(
            model_name='staticfile',
            name='author',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='创建者'),
        ),
        migrations.AddField(
            model_name='challenge',
            name='static_files',
            field=models.ForeignKey(blank=True, help_text='选择要使用的静态文件（仅用于静态文件部署）', null=True, on_delete=django.db.models.deletion.SET_NULL, to='challenge.staticfile', verbose_name='静态文件'),
        ),
        migrations.AddField(
            model_name='challenge',
            name='tags',
            field=models.ManyToManyField(blank=True, to='challenge.tag', verbose_name='标签'),
        ),
    ]
