# Generated by Django 5.1.6 on 2025-02-26 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenge',
            name='flag_template',
            field=models.CharField(default='flag{{{uuid}_{user}_{prefix}_{hash}}}', help_text='用于生成动态Flag的模板', max_length=255, verbose_name='Flag模板'),
        ),
    ]
