# Generated by Django 5.1.6 on 2025-02-27 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0003_alter_challenge_flag_template'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='challenge',
            name='docker_images',
        ),
        migrations.AlterField(
            model_name='challenge',
            name='deployment_type',
            field=models.CharField(choices=[('STATIC', '静态文件部署'), ('COMPOSE', 'Docker Compose部署')], default='STATIC', max_length=10, verbose_name='部署类型'),
        ),
        migrations.DeleteModel(
            name='DockerImages',
        ),
    ]
