# Generated by Django 5.1.6 on 2025-04-22 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0004_remove_challenge_docker_images_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='challenge',
            name='deployment_type',
        ),
    ]
