# Generated by Django 5.1.6 on 2025-04-29 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0006_alter_challenge_docker_compose_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='challenge',
            name='first_blood_time',
        ),
        migrations.RemoveField(
            model_name='challenge',
            name='first_blood_user',
        ),
        migrations.AlterField(
            model_name='challenge',
            name='flag_template',
            field=models.CharField(blank=True, help_text='静态的FLAG值的模板', max_length=255, null=True, verbose_name='Flag值'),
        ),
    ]
