# Generated by Django 5.1.6 on 2025-09-05 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0007_remove_challenge_first_blood_time_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='challenge',
            options={'verbose_name': '题目管理', 'verbose_name_plural': '题目管理'},
        ),
        migrations.AlterModelOptions(
            name='dockercompose',
            options={'verbose_name': '容器镜像管理', 'verbose_name_plural': '容器镜像管理'},
        ),
    ]
