# Generated by Django 5.1.6 on 2026-03-08 18:21

import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.utils.timezone
import imagekit.models.fields
import oauth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ouser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('link', models.URLField(blank=True, help_text='提示：网址必须填写以http开头的完整形式', verbose_name='个人网址')),
                ('avatar', imagekit.models.fields.ProcessedImageField(default='avatar/default/default.png', upload_to='avatar/upload/%Y/%m/%d/%H-%M-%S', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif'], message='只支持jpg、jpeg、png、gif格式的图片')], verbose_name='头像')),
                ('is_member', models.BooleanField(default=False, editable=False, help_text='根据会员有效期自动判断', verbose_name='是否为会员')),
                ('member_since', models.DateTimeField(blank=True, help_text='会员权限开始时间', null=True, verbose_name='会员开始时间')),
                ('member_until', models.DateTimeField(blank=True, help_text='会员权限结束时间', null=True, verbose_name='会员结束时间')),
                ('uuid', models.BigIntegerField(default=oauth.models.generate_numeric_id, editable=False, unique=True, verbose_name='用户ID')),
                ('_encrypted_real_name', models.CharField(blank=True, db_column='real_name', max_length=255, null=True, verbose_name='真实姓名(加密)')),
                ('_encrypted_phones', models.CharField(blank=True, db_column='phones', max_length=255, null=True, verbose_name='手机号(加密)')),
                ('_encrypted_department', models.CharField(blank=True, db_column='department', max_length=255, null=True, verbose_name='学院/部门(加密)')),
                ('_encrypted_student_id', models.CharField(blank=True, db_column='student_id', max_length=255, null=True, verbose_name='学号/工号(加密)')),
                ('profile', models.TextField(blank=True, help_text='提示：个人简介字数限制在100字以内', max_length=100, null=True, verbose_name='个人简介')),
                ('invite_code', models.CharField(blank=True, help_text='用户唯一邀请码', max_length=8, null=True, unique=True, verbose_name='邀请码')),
                ('invite_code_expires', models.DateTimeField(blank=True, null=True, verbose_name='邀请码过期时间')),
            ],
            options={
                'verbose_name': '用户',
                'verbose_name_plural': '用户',
                'ordering': ['-id'],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
