# Generated by Django 5.1.6 on 2026-03-08 18:21

import django.contrib.auth.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0009_emailaddress_unique_primary_email'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('oauth', '0001_initial'),
        ('public', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCTFData',
            fields=[
            ],
            options={
                'verbose_name': '用户CTF数据',
                'verbose_name_plural': '用户数据管理',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('public.ctfuser',),
        ),
        migrations.CreateModel(
            name='UserEmailAddress',
            fields=[
            ],
            options={
                'verbose_name': '用户邮箱',
                'verbose_name_plural': '邮箱管理',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('account.emailaddress',),
        ),
        migrations.CreateModel(
            name='UserGroup',
            fields=[
            ],
            options={
                'verbose_name': '用户组',
                'verbose_name_plural': '用户组管理',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('auth.group',),
            managers=[
                ('objects', django.contrib.auth.models.GroupManager()),
            ],
        ),
        migrations.AddField(
            model_name='ouser',
            name='following',
            field=models.ManyToManyField(blank=True, related_name='followers', to=settings.AUTH_USER_MODEL, verbose_name='关注'),
        ),
        migrations.AddField(
            model_name='ouser',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='ouser',
            name='invited_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invitees', to=settings.AUTH_USER_MODEL, verbose_name='邀请人'),
        ),
        migrations.AddField(
            model_name='ouser',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
    ]
