# Generated by Django 5.1.6 on 2026-03-08 18:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('competition', '0002_initial'),
        ('container', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='containerengineconfig',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='最后修改人'),
        ),
        migrations.AddField(
            model_name='dockerimage',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='创建者'),
        ),
        migrations.AddField(
            model_name='dockerimage',
            name='reviewer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_docker_images', to=settings.AUTH_USER_MODEL, verbose_name='审核人'),
        ),
        migrations.AddField(
            model_name='networktopologyconfig',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='创建者'),
        ),
        migrations.AddField(
            model_name='staticfile',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='创建者'),
        ),
        migrations.AddField(
            model_name='staticfile',
            name='reviewer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_static_files', to=settings.AUTH_USER_MODEL, verbose_name='审核人'),
        ),
        migrations.AddField(
            model_name='usercontainer',
            name='competition',
            field=models.ForeignKey(blank=True, help_text='如果是比赛容器，关联到具体比赛', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_containers', to='competition.competition', verbose_name='所属比赛'),
        ),
        migrations.AddField(
            model_name='usercontainer',
            name='docker_engine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='container.dockerengine', verbose_name='Docker引擎'),
        ),
        migrations.AddField(
            model_name='usercontainer',
            name='topology_config',
            field=models.ForeignKey(blank=True, help_text='如果是拓扑场景，关联到具体的拓扑配置', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_containers', to='container.networktopologyconfig', verbose_name='网络拓扑配置'),
        ),
        migrations.AddField(
            model_name='usercontainer',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
        migrations.AddIndex(
            model_name='usercontainer',
            index=models.Index(fields=['user', 'status'], name='container_u_user_id_528645_idx'),
        ),
        migrations.AddIndex(
            model_name='usercontainer',
            index=models.Index(fields=['challenge_uuid', 'status'], name='container_u_challen_5d356f_idx'),
        ),
        migrations.AddIndex(
            model_name='usercontainer',
            index=models.Index(fields=['expires_at', 'status'], name='container_u_expires_f9fa53_idx'),
        ),
        migrations.AddIndex(
            model_name='usercontainer',
            index=models.Index(fields=['container_type', 'status'], name='container_u_contain_9eb884_idx'),
        ),
        migrations.AddIndex(
            model_name='usercontainer',
            index=models.Index(fields=['competition', 'status'], name='container_u_competi_59107e_idx'),
        ),
    ]
